from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from io import BytesIO
import hashlib
import json
from pathlib import Path
from typing import Any, BinaryIO
import zipfile

import numpy as np
import pandas as pd
from openpyxl import Workbook, load_workbook
from openpyxl.comments import Comment
from openpyxl.styles import Font, PatternFill, Protection
from openpyxl.utils import get_column_letter


FORECAST_HORIZON_QUARTERS = 12
TEMPLATE_FILENAME = "NLTF_forecast_input_template_12q.xlsx"
FORECAST_RUNNER_VERSION = "forecast-runner-v1-governed-gap-aware"
FORECAST_BUILDER_TITLE = "Forecast Builder"
FORECAST_BUILDER_NOTE = (
    "This workflow creates forward forecasts or governed missing-capability gaps from a user-supplied "
    "12-quarter assumption workbook. It writes separate forecast-run artifacts and does not alter governance "
    "evidence, KPIs, MAPE/R2, chart sources, finalists, scenarios, stress tests or diagnostics."
)

STREAM_ORDER = ["PED", "LIGHT_RUC", "HEAVY_RUC"]
STREAM_LABELS = {
    "PED": "PED VKT per capita",
    "LIGHT_RUC": "Light RUC volume",
    "HEAVY_RUC": "Heavy RUC volume",
}
SHEET_BY_STREAM = {
    "PED": "PED Inputs",
    "LIGHT_RUC": "Light RUC Inputs",
    "HEAVY_RUC": "Heavy RUC Inputs",
}
FINALIST_BY_STREAM = {
    "PED": "PED__RESCUE_static_annual_weighted_top12_capnone",
    "LIGHT_RUC": "dynamic_RESID_GBR_n150_d1_lr0.05_w36",
    "HEAVY_RUC": "HEAVY_RUC__RECON_STATIC_REBUILT",
}
MISSING_CAPABILITY_BY_STREAM = {
    "PED": "ped_inner_hpo_static_solver_fitted_state_missing",
    "LIGHT_RUC": "light_ruc_ols_gbm_fitted_state_missing",
    "HEAVY_RUC": "heavy_ruc_component_fitted_state_missing",
}
MISSING_CAPABILITY_NOTES = {
    "PED": (
        "Repo-local PED packs prove stored component-prediction replay and training-fit R2, but do not include "
        "the fitted inner HPO/static-solver objects required to score new assumption rows."
    ),
    "LIGHT_RUC": (
        "Repo-local Light RUC packs prove backtest replay and training-fit R2, but do not include the fitted "
        "OLS base coefficients plus GBM residual model state required for new forward rows."
    ),
    "HEAVY_RUC": (
        "Repo-local Heavy RUC packs prove weighted replay from stored component predictions, but do not include "
        "the four fitted component model states required to generate new component predictions."
    ),
}


@dataclass(frozen=True)
class TemplateColumn:
    name: str
    role: str
    required: bool
    description: str
    formula_key: str | None = None


COMMON_SYSTEM_COLUMNS = [
    TemplateColumn("period", "system", True, "Forecast quarter label generated by the template, for example 2026Q1."),
    TemplateColumn("year", "system", True, "Calendar year for the forecast quarter."),
    TemplateColumn("quarter", "system", True, "Calendar quarter number, 1 through 4."),
    TemplateColumn("horizon", "system", True, "Forecast horizon from the last known actual quarter."),
]

COMMON_FORMULA_COLUMNS = [
    TemplateColumn("q2_dummy", "formula", True, "1 when quarter is Q2, otherwise 0.", "q2_dummy"),
    TemplateColumn("q3_dummy", "formula", True, "1 when quarter is Q3, otherwise 0.", "q3_dummy"),
    TemplateColumn("q4_dummy", "formula", True, "1 when quarter is Q4, otherwise 0.", "q4_dummy"),
    TemplateColumn("post_2020_dummy", "formula", True, "1 for quarters after 2020, otherwise 0.", "post_2020_dummy"),
    TemplateColumn("trend_index", "formula", True, "Sequential time index used by static specifications.", "trend_index"),
]

PED_COLUMNS = [
    *COMMON_SYSTEM_COLUMNS,
    TemplateColumn("real_gdp_per_capita_nzd", "user", True, "User-entered real GDP per capita assumption."),
    TemplateColumn("population", "user", True, "User-entered population assumption."),
    TemplateColumn("unemployment_rate", "user", True, "User-entered unemployment rate assumption in percentage points."),
    TemplateColumn("real_petrol_price_cents_per_litre", "user", True, "User-entered real petrol price assumption."),
    TemplateColumn("target_lag_1", "user", True, "Most recent PED VKT per capita value available before this forecast quarter."),
    TemplateColumn("target_lag_4", "user", True, "PED VKT per capita value four quarters before this forecast quarter."),
    *COMMON_FORMULA_COLUMNS,
    TemplateColumn("log_real_gdp_per_capita", "formula", True, "Natural log of real GDP per capita.", "log_real_gdp_per_capita_nzd"),
    TemplateColumn("log_population", "formula", True, "Natural log of population.", "log_population"),
    TemplateColumn("log_unemployment_rate", "formula", True, "Natural log of unemployment rate.", "log_unemployment_rate"),
    TemplateColumn("log_real_petrol_price", "formula", True, "Natural log of real petrol price.", "log_real_petrol_price_cents_per_litre"),
    TemplateColumn("log_target_lag_1", "formula", True, "Natural log of target lag 1.", "log_target_lag_1"),
    TemplateColumn("log_target_lag_4", "formula", True, "Natural log of target lag 4.", "log_target_lag_4"),
    TemplateColumn("diff_log_target_lag_1_lag_4", "formula", True, "Log target lag 1 minus log target lag 4.", "diff_log_target"),
    TemplateColumn("gdp_petrol_interaction", "formula", True, "Log real GDP per capita multiplied by log real petrol price.", "gdp_petrol_interaction"),
    TemplateColumn("post_2011_x_log_trend", "formula", True, "Post-2011 dummy multiplied by log trend index.", "post_2011_x_log_trend"),
]

LIGHT_RUC_COLUMNS = [
    *COMMON_SYSTEM_COLUMNS,
    TemplateColumn("real_gdp_sa_nzd", "user", True, "User-entered real GDP assumption."),
    TemplateColumn("real_diesel_price_cents_per_litre", "user", True, "User-entered real diesel price assumption."),
    TemplateColumn("real_light_ruc_price_nzd_per_1000km", "user", True, "User-entered real Light RUC price assumption."),
    TemplateColumn("lagged_real_light_ruc_price_nzd_per_1000km", "user", True, "Real Light RUC price lag available before this forecast quarter."),
    TemplateColumn("target_lag_1", "user", True, "Most recent Light RUC volume available before this forecast quarter."),
    TemplateColumn("target_lag_4", "user", True, "Light RUC volume four quarters before this forecast quarter."),
    *COMMON_FORMULA_COLUMNS,
    TemplateColumn("log_real_gdp", "formula", True, "Natural log of real GDP.", "log_real_gdp_sa_nzd"),
    TemplateColumn("log_real_diesel_price", "formula", True, "Natural log of real diesel price.", "log_real_diesel_price_cents_per_litre"),
    TemplateColumn("log_real_light_ruc_price", "formula", True, "Natural log of real Light RUC price.", "log_real_light_ruc_price_nzd_per_1000km"),
    TemplateColumn("log_lagged_real_light_ruc_price", "formula", True, "Natural log of lagged real Light RUC price.", "log_lagged_real_light_ruc_price_nzd_per_1000km"),
    TemplateColumn("log_target_lag_1", "formula", True, "Natural log of target lag 1.", "log_target_lag_1"),
    TemplateColumn("log_target_lag_4", "formula", True, "Natural log of target lag 4.", "log_target_lag_4"),
    TemplateColumn("diff_log_real_gdp", "formula", True, "Quarterly difference in log real GDP.", "diff_log_real_gdp"),
    TemplateColumn("gdp_light_ruc_price_interaction", "formula", True, "Log real GDP multiplied by log real Light RUC price.", "gdp_light_ruc_price_interaction"),
]

HEAVY_RUC_COLUMNS = [
    *COMMON_SYSTEM_COLUMNS,
    TemplateColumn("real_gdp_sa_nzd", "user", True, "User-entered real GDP assumption."),
    TemplateColumn("real_diesel_price_cents_per_litre", "user", True, "User-entered real diesel price assumption."),
    TemplateColumn("unemployment_rate", "user", True, "User-entered unemployment rate assumption in percentage points."),
    TemplateColumn("real_light_ruc_price_nzd_per_1000km", "user", True, "User-entered real Light RUC price assumption used by Heavy components."),
    TemplateColumn("lagged_real_light_ruc_price_nzd_per_1000km", "user", True, "Real Light RUC price lag used by Heavy components."),
    TemplateColumn("real_heavy_ruc_price_nzd_per_1000km", "user", True, "User-entered real Heavy RUC price assumption."),
    TemplateColumn("lead_real_heavy_ruc_price_nzd_per_1000km", "user", True, "Expected next-quarter real Heavy RUC price assumption."),
    TemplateColumn("target_lag_1", "user", True, "Most recent Heavy RUC volume available before this forecast quarter."),
    TemplateColumn("target_lag_4", "user", True, "Heavy RUC volume four quarters before this forecast quarter."),
    *COMMON_FORMULA_COLUMNS,
    TemplateColumn("log_real_gdp", "formula", True, "Natural log of real GDP.", "log_real_gdp_sa_nzd"),
    TemplateColumn("log_real_diesel_price", "formula", True, "Natural log of real diesel price.", "log_real_diesel_price_cents_per_litre"),
    TemplateColumn("log_unemployment_rate", "formula", True, "Natural log of unemployment rate.", "log_unemployment_rate"),
    TemplateColumn("log_real_light_ruc_price", "formula", True, "Natural log of real Light RUC price.", "log_real_light_ruc_price_nzd_per_1000km"),
    TemplateColumn("log_lagged_real_light_ruc_price", "formula", True, "Natural log of lagged real Light RUC price.", "log_lagged_real_light_ruc_price_nzd_per_1000km"),
    TemplateColumn("log_real_heavy_ruc_price", "formula", True, "Natural log of real Heavy RUC price.", "log_real_heavy_ruc_price_nzd_per_1000km"),
    TemplateColumn("log_lead_real_heavy_ruc_price", "formula", True, "Natural log of lead real Heavy RUC price.", "log_lead_real_heavy_ruc_price_nzd_per_1000km"),
    TemplateColumn("log_target_lag_1", "formula", True, "Natural log of target lag 1.", "log_target_lag_1"),
    TemplateColumn("log_target_lag_4", "formula", True, "Natural log of target lag 4.", "log_target_lag_4"),
    TemplateColumn("diff_log_real_gdp", "formula", True, "Quarterly difference in log real GDP.", "diff_log_real_gdp"),
    TemplateColumn("gdp_heavy_ruc_price_interaction", "formula", True, "Log real GDP multiplied by log real Heavy RUC price.", "gdp_heavy_ruc_price_interaction"),
]

STREAM_COLUMNS = {
    "PED": PED_COLUMNS,
    "LIGHT_RUC": LIGHT_RUC_COLUMNS,
    "HEAVY_RUC": HEAVY_RUC_COLUMNS,
}


@dataclass
class ForecastValidationResult:
    valid: bool
    errors: list[str]
    warnings: list[str]
    assumptions: pd.DataFrame
    latest_actual_period: str
    forecast_periods: list[str]

    def report_frame(self) -> pd.DataFrame:
        rows = [
            {"severity": "error", "message": message}
            for message in self.errors
        ] + [
            {"severity": "warning", "message": message}
            for message in self.warnings
        ]
        if not rows:
            rows = [{"severity": "ok", "message": "Workbook inputs passed structural and required-value validation."}]
        return pd.DataFrame(rows)


@dataclass
class ForecastRunResult:
    output_dir: Path
    manifest: dict[str, Any]
    validation: ForecastValidationResult
    future_forecasts: pd.DataFrame
    component_forecasts: pd.DataFrame
    assumptions: pd.DataFrame
    report_markdown: str

    @property
    def has_numeric_forecasts(self) -> bool:
        if self.future_forecasts.empty or "forecast" not in self.future_forecasts.columns:
            return False
        return pd.to_numeric(self.future_forecasts["forecast"], errors="coerce").notna().any()


def repo_root_from_here() -> Path:
    return Path(__file__).resolve().parents[1]


def latest_known_actual_period(repo_root: Path | str | None = None) -> str:
    root = Path(repo_root) if repo_root is not None else repo_root_from_here()
    candidates = [
        root / "data" / "dashboard_evidence_pack" / "data" / "scorecard_predictions.parquet",
        root / "data" / "dashboard_evidence_pack" / "data" / "component_predictions.parquet",
    ]
    periods: list[str] = []
    for path in candidates:
        if not path.exists():
            continue
        try:
            frame = pd.read_parquet(path, columns=["target_period"])
        except Exception:
            frame = pd.read_parquet(path)
        if "target_period" in frame.columns:
            periods.extend(frame["target_period"].dropna().astype(str).tolist())
    if not periods:
        return "2025Q4"
    return max(periods, key=quarter_sort_key)


def quarter_sort_key(period: str) -> int:
    year, quarter = parse_period(period)
    return year * 4 + quarter


def parse_period(period: str) -> tuple[int, int]:
    text = str(period).strip().upper()
    if "Q" not in text:
        raise ValueError(f"Invalid quarter period: {period!r}")
    year_text, quarter_text = text.split("Q", 1)
    year = int(year_text)
    quarter = int(quarter_text)
    if quarter not in {1, 2, 3, 4}:
        raise ValueError(f"Invalid quarter number in period: {period!r}")
    return year, quarter


def add_quarters(period: str, quarters: int) -> str:
    year, quarter = parse_period(period)
    index = year * 4 + (quarter - 1) + quarters
    return f"{index // 4}Q{(index % 4) + 1}"


def future_quarters_after(period: str, horizon: int = FORECAST_HORIZON_QUARTERS) -> list[str]:
    return [add_quarters(period, offset) for offset in range(1, horizon + 1)]


def build_forecast_input_template(
    output_path: Path | str,
    repo_root: Path | str | None = None,
) -> Path:
    root = Path(repo_root) if repo_root is not None else repo_root_from_here()
    latest = latest_known_actual_period(root)
    periods = future_quarters_after(latest)
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)

    wb = Workbook()
    readme = wb.active
    readme.title = "README"
    _write_readme_sheet(readme, latest, periods)
    for stream in STREAM_ORDER:
        ws = wb.create_sheet(SHEET_BY_STREAM[stream])
        _write_input_sheet(ws, stream, periods)
    wb.save(output)
    return output


def build_forecast_input_template_bytes(repo_root: Path | str | None = None) -> bytes:
    stream = BytesIO()
    root = Path(repo_root) if repo_root is not None else repo_root_from_here()
    latest = latest_known_actual_period(root)
    periods = future_quarters_after(latest)
    wb = Workbook()
    readme = wb.active
    readme.title = "README"
    _write_readme_sheet(readme, latest, periods)
    for stream_code in STREAM_ORDER:
        ws = wb.create_sheet(SHEET_BY_STREAM[stream_code])
        _write_input_sheet(ws, stream_code, periods)
    wb.save(stream)
    return stream.getvalue()


def _write_readme_sheet(ws: Any, latest_period: str, periods: list[str]) -> None:
    ws["A1"] = "NLTF 12-quarter forecast input template"
    ws["A1"].font = Font(bold=True, size=14, color="002B5C")
    rows = [
        ("Latest known actual quarter", latest_period),
        ("Forecast horizon", f"{periods[0]} to {periods[-1]}"),
        ("What to fill", "Only fill the user-entry columns in PED Inputs, Light RUC Inputs and Heavy RUC Inputs."),
        ("What not to edit", "Do not edit period, year, quarter, horizon or protected formula columns."),
        ("Data rule", "Use real price/GDP assumptions in the units named in each header."),
        ("Governance rule", "The runner does not run a broad candidate search and never overwrites dashboard evidence packs."),
        (
            "Missing model-state rule",
            "If repo-local fitted finalist artifacts are unavailable, the runner writes governed gaps instead of fake forecasts.",
        ),
    ]
    for row_index, (label, value) in enumerate(rows, start=3):
        ws.cell(row=row_index, column=1, value=label).font = Font(bold=True)
        ws.cell(row=row_index, column=2, value=value)
    ws.column_dimensions["A"].width = 32
    ws.column_dimensions["B"].width = 118
    ws.freeze_panes = "A3"


def _write_input_sheet(ws: Any, stream: str, periods: list[str]) -> None:
    columns = STREAM_COLUMNS[stream]
    header_fill = PatternFill("solid", fgColor="EAF2F8")
    user_fill = PatternFill("solid", fgColor="FFF7CC")
    formula_fill = PatternFill("solid", fgColor="E7F5EC")
    system_fill = PatternFill("solid", fgColor="E6EDF5")
    for col_index, column in enumerate(columns, start=1):
        cell = ws.cell(row=1, column=col_index, value=column.name)
        cell.font = Font(bold=True, color="002B5C")
        cell.fill = header_fill
        cell.comment = Comment(f"{column.role.upper()}: {column.description}", "Codex")
        ws.column_dimensions[get_column_letter(col_index)].width = max(15, min(34, len(column.name) + 3))

    col_map = {column.name: idx for idx, column in enumerate(columns, start=1)}
    for row_offset, period in enumerate(periods, start=2):
        year, quarter = parse_period(period)
        system_values = {
            "period": period,
            "year": year,
            "quarter": quarter,
            "horizon": row_offset - 1,
        }
        for column in columns:
            cell = ws.cell(row=row_offset, column=col_map[column.name])
            if column.role == "system":
                cell.value = system_values[column.name]
                cell.fill = system_fill
            elif column.role == "formula":
                cell.value = _excel_formula(column.formula_key or column.name, row_offset, col_map)
                cell.fill = formula_fill
            else:
                cell.fill = user_fill
                cell.protection = Protection(locked=False)
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = ws.dimensions
    ws.protection.sheet = True
    ws.protection.enable()


def _cell(row: int, col_map: dict[str, int], column: str) -> str:
    return f"{get_column_letter(col_map[column])}{row}"


def _excel_formula(formula_key: str, row: int, col_map: dict[str, int]) -> str:
    q = _cell(row, col_map, "quarter")
    year = _cell(row, col_map, "year")
    horizon = _cell(row, col_map, "horizon")
    if formula_key == "q2_dummy":
        return f'=IF({q}=2,1,0)'
    if formula_key == "q3_dummy":
        return f'=IF({q}=3,1,0)'
    if formula_key == "q4_dummy":
        return f'=IF({q}=4,1,0)'
    if formula_key == "post_2020_dummy":
        return f'=IF({year}>=2021,1,0)'
    if formula_key == "trend_index":
        return f"={horizon}+104"
    if formula_key == "diff_log_real_gdp":
        current = _cell(row, col_map, "log_real_gdp")
        if row == 2:
            return '=""'
        previous = _cell(row - 1, col_map, "log_real_gdp")
        return f'=IF(AND({current}<>"",{previous}<>""),{current}-{previous},"")'
    if formula_key == "diff_log_target":
        lag1 = _cell(row, col_map, "log_target_lag_1")
        lag4 = _cell(row, col_map, "log_target_lag_4")
        return f'=IF(AND({lag1}<>"",{lag4}<>""),{lag1}-{lag4},"")'
    if formula_key == "gdp_petrol_interaction":
        gdp = _cell(row, col_map, "log_real_gdp_per_capita")
        price = _cell(row, col_map, "log_real_petrol_price")
        return f'=IF(AND({gdp}<>"",{price}<>""),{gdp}*{price},"")'
    if formula_key == "gdp_light_ruc_price_interaction":
        gdp = _cell(row, col_map, "log_real_gdp")
        price = _cell(row, col_map, "log_real_light_ruc_price")
        return f'=IF(AND({gdp}<>"",{price}<>""),{gdp}*{price},"")'
    if formula_key == "gdp_heavy_ruc_price_interaction":
        gdp = _cell(row, col_map, "log_real_gdp")
        price = _cell(row, col_map, "log_real_heavy_ruc_price")
        return f'=IF(AND({gdp}<>"",{price}<>""),{gdp}*{price},"")'
    if formula_key == "post_2011_x_log_trend":
        trend = _cell(row, col_map, "trend_index")
        return f'=IF({trend}>0,LN({trend}),"")'
    if formula_key.startswith("log_"):
        source = formula_key.removeprefix("log_")
        source_cell = _cell(row, col_map, source)
        return f'=IF({source_cell}>0,LN({source_cell}),"")'
    return '=""'


def validate_forecast_workbook(
    workbook: Path | str | bytes | BinaryIO,
    repo_root: Path | str | None = None,
) -> ForecastValidationResult:
    root = Path(repo_root) if repo_root is not None else repo_root_from_here()
    latest = latest_known_actual_period(root)
    periods = future_quarters_after(latest)
    errors: list[str] = []
    warnings: list[str] = []
    frames: list[pd.DataFrame] = []
    try:
        wb = _load_workbook_from_input(workbook)
    except Exception as exc:
        return ForecastValidationResult(False, [f"Workbook could not be opened: {exc}"], [], pd.DataFrame(), latest, periods)

    for stream in STREAM_ORDER:
        sheet = SHEET_BY_STREAM[stream]
        if sheet not in wb.sheetnames:
            errors.append(f"Missing required sheet: {sheet}")
            continue
        frame = _worksheet_to_frame(wb[sheet])
        sheet_errors, sheet_warnings = _validate_sheet_frame(frame, stream, periods)
        errors.extend(sheet_errors)
        warnings.extend(sheet_warnings)
        if not frame.empty:
            frames.append(_build_stream_assumptions(frame, stream, periods))

    assumptions = pd.concat(frames, ignore_index=True, sort=False) if frames else pd.DataFrame()
    return ForecastValidationResult(not errors, errors, warnings, assumptions, latest, periods)


def run_forecast_workbook(
    workbook: Path | str | bytes | BinaryIO,
    output_dir: Path | str | None = None,
    repo_root: Path | str | None = None,
    workbook_filename: str | None = None,
    run_timestamp: str | None = None,
) -> ForecastRunResult:
    root = Path(repo_root) if repo_root is not None else repo_root_from_here()
    validation = validate_forecast_workbook(workbook, root)
    timestamp = run_timestamp or datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    run_dir = Path(output_dir) if output_dir is not None else root / "artifacts" / "forecast_runs" / timestamp
    run_dir.mkdir(parents=True, exist_ok=True)
    workbook_bytes = _workbook_bytes(workbook)
    workbook_hash = hashlib.sha256(workbook_bytes).hexdigest() if workbook_bytes else None

    capabilities = model_capability_gap_register(root)
    future = _future_forecast_rows(validation, capabilities)
    components = _component_forecast_rows(validation, capabilities, root)
    assumptions = validation.assumptions.copy()
    report = _forecast_validation_report(validation, capabilities)
    manifest = {
        "run_id": timestamp,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "forecast_runner_version": FORECAST_RUNNER_VERSION,
        "workbook_filename": workbook_filename or _workbook_name(workbook),
        "workbook_sha256": workbook_hash,
        "latest_actual_period": validation.latest_actual_period,
        "forecast_periods": validation.forecast_periods,
        "validation_status": "passed" if validation.valid else "failed",
        "validation_errors": validation.errors,
        "validation_warnings": validation.warnings,
        "fixed_finalists_only": True,
        "broad_search_run": False,
        "evidence_pack_modified": False,
        "chart_sources_modified": False,
        "forecast_status": "governed_gap" if not _any_forecast_available(capabilities) else "available",
        "model_capabilities": capabilities.to_dict(orient="records"),
        "output_files": [
            "future_forecasts.parquet",
            "component_forecasts.parquet",
            "forecast_assumptions.parquet",
            "forecast_run_manifest.json",
            "forecast_validation_report.md",
            "future_forecasts.csv",
            "component_forecasts.csv",
        ],
    }

    future.to_parquet(run_dir / "future_forecasts.parquet", index=False)
    components.to_parquet(run_dir / "component_forecasts.parquet", index=False)
    assumptions.to_parquet(run_dir / "forecast_assumptions.parquet", index=False)
    future.to_csv(run_dir / "future_forecasts.csv", index=False)
    components.to_csv(run_dir / "component_forecasts.csv", index=False)
    assumptions.to_csv(run_dir / "forecast_assumptions.csv", index=False)
    (run_dir / "forecast_run_manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    (run_dir / "forecast_validation_report.md").write_text(report, encoding="utf-8")

    return ForecastRunResult(
        output_dir=run_dir,
        manifest=manifest,
        validation=validation,
        future_forecasts=future,
        component_forecasts=components,
        assumptions=assumptions,
        report_markdown=report,
    )


def forecast_pack_zip_bytes(output_dir: Path | str) -> bytes:
    root = Path(output_dir)
    stream = BytesIO()
    with zipfile.ZipFile(stream, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for path in sorted(root.glob("*")):
            if path.is_file():
                zf.write(path, arcname=path.name)
    return stream.getvalue()


def create_completed_sample_workbook(
    output_path: Path | str,
    repo_root: Path | str | None = None,
) -> Path:
    path = build_forecast_input_template(output_path, repo_root=repo_root)
    wb = load_workbook(path)
    sample_values = {
        "real_gdp_per_capita_nzd": 72000.0,
        "population": 5300000.0,
        "unemployment_rate": 4.2,
        "real_petrol_price_cents_per_litre": 265.0,
        "real_gdp_sa_nzd": 320000000000.0,
        "real_diesel_price_cents_per_litre": 232.0,
        "real_light_ruc_price_nzd_per_1000km": 84.0,
        "lagged_real_light_ruc_price_nzd_per_1000km": 82.0,
        "real_heavy_ruc_price_nzd_per_1000km": 188.0,
        "lead_real_heavy_ruc_price_nzd_per_1000km": 190.0,
        "target_lag_1": 1000.0,
        "target_lag_4": 980.0,
    }
    for stream in STREAM_ORDER:
        ws = wb[SHEET_BY_STREAM[stream]]
        headers = {cell.value: cell.column for cell in ws[1] if cell.value}
        ws.protection.sheet = False
        for row in range(2, 2 + FORECAST_HORIZON_QUARTERS):
            for name, value in sample_values.items():
                if name in headers:
                    multiplier = 1.0 + ((row - 2) * 0.004)
                    ws.cell(row=row, column=headers[name], value=value * multiplier)
        ws.protection.sheet = True
    wb.save(path)
    return path


def model_capability_gap_register(repo_root: Path | str | None = None) -> pd.DataFrame:
    root = Path(repo_root) if repo_root is not None else repo_root_from_here()
    model_artifact_glob = ["*.pkl", "*.pickle", "*.joblib"]
    rows: list[dict[str, Any]] = []
    for stream in STREAM_ORDER:
        stream_root = root / "data" / "dashboard_evidence_pack_reproducibility" / stream.lower()
        if stream == "LIGHT_RUC":
            stream_root = root / "data" / "dashboard_evidence_pack_reproducibility" / "light_ruc"
        if stream == "HEAVY_RUC":
            stream_root = root / "data" / "dashboard_evidence_pack_reproducibility" / "heavy_ruc"
        if stream == "PED":
            stream_root = root / "data" / "dashboard_evidence_pack_reproducibility" / "ped_inner_hpo"
        model_artifacts = [
            path
            for pattern in model_artifact_glob
            for path in stream_root.rglob(pattern)
            if path.is_file()
        ] if stream_root.exists() else []
        available = bool(model_artifacts)
        rows.append(
            {
                "stream": stream,
                "stream_label": STREAM_LABELS[stream],
                "model": FINALIST_BY_STREAM[stream],
                "forecast_capability_available": available,
                "capability_status": "available" if available else "governed_gap",
                "gap_code": None if available else MISSING_CAPABILITY_BY_STREAM[stream],
                "gap_reason": "" if available else MISSING_CAPABILITY_NOTES[stream],
                "repo_artifact_basis": "; ".join(_repo_relative(root, path) for path in model_artifacts) if available else _capability_basis(root, stream),
                "required_for_forward_forecast": True,
            }
        )
    return pd.DataFrame(rows)


def _capability_basis(root: Path, stream: str) -> str:
    paths = [
        root / "data" / "dashboard_evidence_pack" / "data" / "model_registry.parquet",
        root / "data" / "dashboard_evidence_pack" / "data" / "model_coefficients.parquet",
    ]
    if stream == "PED":
        paths.append(root / "data" / "dashboard_evidence_pack_reproducibility" / "ped_inner_hpo" / "model_coefficients.parquet")
    if stream == "LIGHT_RUC":
        paths.append(root / "data" / "dashboard_evidence_pack_reproducibility" / "light_ruc" / "model_coefficients.parquet")
    if stream == "HEAVY_RUC":
        paths.append(root / "data" / "dashboard_evidence_pack_reproducibility" / "heavy_ruc" / "model_coefficients.parquet")
    return "; ".join(_repo_relative(root, path) for path in paths if path.exists())


def _load_workbook_from_input(workbook: Path | str | bytes | BinaryIO) -> Any:
    if isinstance(workbook, bytes):
        return load_workbook(BytesIO(workbook), data_only=False)
    if hasattr(workbook, "read"):
        content = workbook.read()
        if hasattr(workbook, "seek"):
            workbook.seek(0)
        return load_workbook(BytesIO(content), data_only=False)
    return load_workbook(Path(workbook), data_only=False)


def _workbook_bytes(workbook: Path | str | bytes | BinaryIO) -> bytes:
    if isinstance(workbook, bytes):
        return workbook
    if hasattr(workbook, "read"):
        content = workbook.read()
        if hasattr(workbook, "seek"):
            workbook.seek(0)
        return content
    path = Path(workbook)
    return path.read_bytes() if path.exists() else b""


def _workbook_name(workbook: Path | str | bytes | BinaryIO) -> str:
    if isinstance(workbook, (str, Path)):
        return Path(workbook).name
    return getattr(workbook, "name", "uploaded_forecast_workbook.xlsx")


def _worksheet_to_frame(ws: Any) -> pd.DataFrame:
    headers = [str(cell.value).strip() if cell.value is not None else "" for cell in ws[1]]
    rows: list[dict[str, Any]] = []
    for row in ws.iter_rows(min_row=2, values_only=True):
        if not any(value is not None for value in row):
            continue
        rows.append({header: value for header, value in zip(headers, row, strict=False) if header})
    return pd.DataFrame(rows)


def _validate_sheet_frame(frame: pd.DataFrame, stream: str, periods: list[str]) -> tuple[list[str], list[str]]:
    errors: list[str] = []
    warnings: list[str] = []
    sheet = SHEET_BY_STREAM[stream]
    expected_headers = [column.name for column in STREAM_COLUMNS[stream]]
    missing_headers = [name for name in expected_headers if name not in frame.columns]
    if missing_headers:
        errors.append(f"{sheet}: missing required headers: {', '.join(missing_headers)}")
        return errors, warnings
    if len(frame) != FORECAST_HORIZON_QUARTERS:
        errors.append(f"{sheet}: expected {FORECAST_HORIZON_QUARTERS} forecast rows, found {len(frame)}")
    observed_periods = frame["period"].dropna().astype(str).str.upper().tolist()
    if observed_periods[:FORECAST_HORIZON_QUARTERS] != periods:
        errors.append(f"{sheet}: period rows must be {periods[0]} through {periods[-1]} with no gaps")
    for column in [col for col in STREAM_COLUMNS[stream] if col.role == "user" and col.required]:
        values = pd.to_numeric(frame[column.name], errors="coerce") if column.name in frame.columns else pd.Series(dtype=float)
        if values.isna().any():
            errors.append(f"{sheet}: required user-entry column {column.name} has missing or non-numeric values")
        elif (values <= 0).any():
            errors.append(f"{sheet}: required user-entry column {column.name} must be positive for log/lag transforms")
    formula_headers = [col.name for col in STREAM_COLUMNS[stream] if col.role == "formula"]
    if not formula_headers:
        warnings.append(f"{sheet}: no formula columns were found")
    return errors, warnings


def _build_stream_assumptions(frame: pd.DataFrame, stream: str, periods: list[str]) -> pd.DataFrame:
    out = frame.copy()
    out = out.head(FORECAST_HORIZON_QUARTERS).copy()
    out["stream"] = stream
    out["stream_label"] = STREAM_LABELS[stream]
    out["model"] = FINALIST_BY_STREAM[stream]
    out["period"] = periods[: len(out)]
    out["year"] = out["period"].map(lambda value: parse_period(value)[0])
    out["quarter"] = out["period"].map(lambda value: parse_period(value)[1])
    out["horizon"] = range(1, len(out) + 1)
    q = pd.to_numeric(out["quarter"], errors="coerce")
    out["q2_dummy"] = q.eq(2).astype(int)
    out["q3_dummy"] = q.eq(3).astype(int)
    out["q4_dummy"] = q.eq(4).astype(int)
    out["post_2020_dummy"] = pd.to_numeric(out["year"], errors="coerce").ge(2021).astype(int)
    out["trend_index"] = out["period"].map(lambda value: quarter_sort_key(value) - quarter_sort_key("2000Q1") + 1)

    for source in [
        "real_gdp_sa_nzd",
        "real_gdp_per_capita_nzd",
        "population",
        "unemployment_rate",
        "real_petrol_price_cents_per_litre",
        "real_diesel_price_cents_per_litre",
        "real_light_ruc_price_nzd_per_1000km",
        "lagged_real_light_ruc_price_nzd_per_1000km",
        "real_heavy_ruc_price_nzd_per_1000km",
        "lead_real_heavy_ruc_price_nzd_per_1000km",
        "target_lag_1",
        "target_lag_4",
    ]:
        if source in out.columns:
            numeric = pd.to_numeric(out[source], errors="coerce")
            out[source] = numeric
            out[f"log_{source}"] = np.where(numeric > 0, np.log(numeric), np.nan)

    if "log_real_gdp_sa_nzd" in out.columns:
        out["diff_log_real_gdp"] = out["log_real_gdp_sa_nzd"].diff()
        out["log_real_gdp"] = out["log_real_gdp_sa_nzd"]
    if "log_real_gdp_per_capita_nzd" in out.columns:
        out["log_real_gdp_per_capita"] = out["log_real_gdp_per_capita_nzd"]
    if "log_real_petrol_price_cents_per_litre" in out.columns:
        out["log_real_petrol_price"] = out["log_real_petrol_price_cents_per_litre"]
    if "log_real_diesel_price_cents_per_litre" in out.columns:
        out["log_real_diesel_price"] = out["log_real_diesel_price_cents_per_litre"]
    if "log_real_light_ruc_price_nzd_per_1000km" in out.columns:
        out["log_real_light_ruc_price"] = out["log_real_light_ruc_price_nzd_per_1000km"]
    if "log_lagged_real_light_ruc_price_nzd_per_1000km" in out.columns:
        out["log_lagged_real_light_ruc_price"] = out["log_lagged_real_light_ruc_price_nzd_per_1000km"]
    if "log_real_heavy_ruc_price_nzd_per_1000km" in out.columns:
        out["log_real_heavy_ruc_price"] = out["log_real_heavy_ruc_price_nzd_per_1000km"]
    if "log_lead_real_heavy_ruc_price_nzd_per_1000km" in out.columns:
        out["log_lead_real_heavy_ruc_price"] = out["log_lead_real_heavy_ruc_price_nzd_per_1000km"]
    if {"log_target_lag_1", "log_target_lag_4"}.issubset(out.columns):
        out["diff_log_target_lag_1_lag_4"] = out["log_target_lag_1"] - out["log_target_lag_4"]
    if {"log_real_gdp_per_capita", "log_real_petrol_price"}.issubset(out.columns):
        out["gdp_petrol_interaction"] = out["log_real_gdp_per_capita"] * out["log_real_petrol_price"]
    if {"log_real_gdp", "log_real_light_ruc_price"}.issubset(out.columns):
        out["gdp_light_ruc_price_interaction"] = out["log_real_gdp"] * out["log_real_light_ruc_price"]
    if {"log_real_gdp", "log_real_heavy_ruc_price"}.issubset(out.columns):
        out["gdp_heavy_ruc_price_interaction"] = out["log_real_gdp"] * out["log_real_heavy_ruc_price"]
    out["post_2011_x_log_trend"] = np.where(out["trend_index"] > 0, np.log(out["trend_index"]), np.nan)
    out["transform_status"] = "built_from_template_inputs"
    return out


def _future_forecast_rows(validation: ForecastValidationResult, capabilities: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    cap_lookup = capabilities.set_index("stream").to_dict(orient="index")
    for stream in STREAM_ORDER:
        cap = cap_lookup[stream]
        for horizon, period in enumerate(validation.forecast_periods, start=1):
            rows.append(
                {
                    "stream": stream,
                    "stream_label": STREAM_LABELS[stream],
                    "model": FINALIST_BY_STREAM[stream],
                    "target_period": period,
                    "horizon": horizon,
                    "forecast": pd.NA,
                    "prediction": pd.NA,
                    "forecast_available": False,
                    "availability_status": "validation_failed" if not validation.valid else cap["capability_status"],
                    "gap_code": "input_validation_failed" if not validation.valid else cap["gap_code"],
                    "gap_reason": "; ".join(validation.errors) if not validation.valid else cap["gap_reason"],
                    "fixed_finalist_only": True,
                    "broad_search_run": False,
                }
            )
    return pd.DataFrame(rows)


def _component_forecast_rows(
    validation: ForecastValidationResult,
    capabilities: pd.DataFrame,
    repo_root: Path,
) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    cap_lookup = capabilities.set_index("stream").to_dict(orient="index")
    components = _component_registry(repo_root)
    for stream in STREAM_ORDER:
        cap = cap_lookup[stream]
        stream_components = components.get(stream, [])
        for horizon, period in enumerate(validation.forecast_periods, start=1):
            for component in stream_components:
                rows.append(
                    {
                        "stream": stream,
                        "stream_label": STREAM_LABELS[stream],
                        "model": FINALIST_BY_STREAM[stream],
                        "component_model": component.get("component_model"),
                        "component_role": component.get("component_role"),
                        "component_weight": component.get("component_weight"),
                        "target_period": period,
                        "horizon": horizon,
                        "component_forecast": pd.NA,
                        "weighted_component_forecast": pd.NA,
                        "forecast_available": False,
                        "availability_status": "validation_failed" if not validation.valid else cap["capability_status"],
                        "gap_code": "input_validation_failed" if not validation.valid else cap["gap_code"],
                        "gap_reason": "; ".join(validation.errors) if not validation.valid else cap["gap_reason"],
                        "fixed_finalist_only": True,
                        "broad_search_run": False,
                    }
                )
    return pd.DataFrame(rows)


def _component_registry(repo_root: Path) -> dict[str, list[dict[str, Any]]]:
    heavy_components: list[dict[str, Any]] = []
    heavy_path = repo_root / "data" / "dashboard_evidence_pack" / "data" / "ensemble_components.parquet"
    if heavy_path.exists():
        try:
            heavy = pd.read_parquet(heavy_path)
            heavy = heavy[heavy["stream"].astype(str).eq("HEAVY_RUC")]
            for _, row in heavy.iterrows():
                heavy_components.append(
                    {
                        "component_model": row.get("component_model"),
                        "component_role": "weighted_ensemble_component",
                        "component_weight": pd.to_numeric(row.get("weight"), errors="coerce"),
                    }
                )
        except Exception:
            heavy_components = []
    return {
        "PED": [
            {
                "component_model": "hpo::PED__HPOREFINE_solver_static_convex_top18",
                "component_role": "outer_hpo_static_solver_component",
                "component_weight": 1.0,
            },
            {
                "component_model": "PED inner HPO/static-solver members",
                "component_role": "inner_component_trace",
                "component_weight": pd.NA,
            },
        ],
        "LIGHT_RUC": [
            {"component_model": "base_schiff_ols", "component_role": "OLS base level prediction", "component_weight": pd.NA},
            {
                "component_model": "residual_gbm_correction",
                "component_role": "GBM residual correction",
                "component_weight": pd.NA,
            },
        ],
        "HEAVY_RUC": heavy_components
        or [
            {"component_model": "C1-C4 heavy RUC components", "component_role": "weighted_ensemble_component", "component_weight": pd.NA}
        ],
    }


def _any_forecast_available(capabilities: pd.DataFrame) -> bool:
    if capabilities.empty or "forecast_capability_available" not in capabilities.columns:
        return False
    return capabilities["forecast_capability_available"].fillna(False).astype(bool).any()


def _forecast_validation_report(validation: ForecastValidationResult, capabilities: pd.DataFrame) -> str:
    lines = [
        "# Forecast validation report",
        "",
        f"- Runner version: `{FORECAST_RUNNER_VERSION}`",
        f"- Latest known actual quarter: `{validation.latest_actual_period}`",
        f"- Forecast horizon: `{validation.forecast_periods[0]}` to `{validation.forecast_periods[-1]}`",
        f"- Input validation: `{'passed' if validation.valid else 'failed'}`",
        "- Broad candidate search run: `false`",
        "- Existing dashboard evidence/KPI/chart-source files modified: `false`",
        "",
        "## Validation messages",
        "",
    ]
    if validation.errors:
        lines.extend(f"- ERROR: {message}" for message in validation.errors)
    if validation.warnings:
        lines.extend(f"- WARNING: {message}" for message in validation.warnings)
    if not validation.errors and not validation.warnings:
        lines.append("- OK: Workbook inputs passed validation.")
    lines.extend(["", "## Forecast capability", ""])
    for _, row in capabilities.iterrows():
        lines.extend(
            [
                f"### {row['stream_label']}",
                "",
                f"- Fixed finalist: `{row['model']}`",
                f"- Status: `{row['capability_status']}`",
                f"- Gap code: `{row['gap_code']}`",
                f"- Reason: {row['gap_reason']}",
                "",
            ]
        )
    return "\n".join(lines).strip() + "\n"


def _repo_relative(root: Path, path: Path) -> str:
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return path.name
