from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from io import BytesIO
import hashlib
import json
from pathlib import Path
from typing import Any, BinaryIO
import zipfile

import numpy as np
import pandas as pd
from openpyxl import Workbook, load_workbook
from openpyxl.comments import Comment
from openpyxl.styles import Font, PatternFill, Protection
from openpyxl.utils import get_column_letter


FORECAST_HORIZON_QUARTERS = 12
TEMPLATE_FILENAME = "NLTF_forecast_input_template_12q.xlsx"
FORECAST_RUNNER_VERSION = "forecast-runner-v2-fixed-finalist-light-ruc"
FORECAST_BUILDER_TITLE = "Forecast Builder"
FORECAST_BUILDER_NOTE = (
    "This workflow creates forward forecasts or governed missing-capability gaps from a user-supplied "
    "12-quarter assumption workbook. It writes separate forecast-run artifacts and does not alter governance "
    "evidence, KPIs, MAPE/R2, chart sources, finalists, scenarios, stress tests or diagnostics."
)

STREAM_ORDER = ["PED", "LIGHT_RUC", "HEAVY_RUC"]
STREAM_LABELS = {
    "PED": "PED VKT per capita",
    "LIGHT_RUC": "Light RUC volume",
    "HEAVY_RUC": "Heavy RUC volume",
}
SHEET_BY_STREAM = {
    "PED": "PED Inputs",
    "LIGHT_RUC": "Light RUC Inputs",
    "HEAVY_RUC": "Heavy RUC Inputs",
}
FINALIST_BY_STREAM = {
    "PED": "PED__RESCUE_static_annual_weighted_top12_capnone",
    "LIGHT_RUC": "dynamic_RESID_GBR_n150_d1_lr0.05_w36",
    "HEAVY_RUC": "HEAVY_RUC__RECON_STATIC_REBUILT",
}
MISSING_CAPABILITY_BY_STREAM = {
    "PED": "ped_inner_hpo_static_solver_forward_scorer_missing",
    "LIGHT_RUC": "light_ruc_fixed_finalist_forward_scorer_missing",
    "HEAVY_RUC": "heavy_ruc_component_forward_scorers_missing",
}
MISSING_CAPABILITY_NOTES = {
    "PED": (
        "PED remains a governed gap for forward scoring: repo-vendored HPO/static-solver artifacts prove stored "
        "component replay and training-fit provenance, but do not provide a verified executable inner HPO/static-solver "
        "forward scorer for new assumption rows. Missing forward state: nested top-member refit registry, feature matrix "
        "builder parity tests, and inner weighted replay parity for new rows."
    ),
    "LIGHT_RUC": (
        "Light RUC requires repo-local model_input_history and the fixed dynamic_RESID_GBR_n150_d1_lr0.05_w36 recipe."
    ),
    "HEAVY_RUC": (
        "Heavy RUC remains a governed gap for forward scoring: repo-local packs prove the final weighted replay from "
        "stored component predictions, but the executable new-row scorers are not yet parity-tested. Missing forward "
        "scorers: C1 ElasticNet dynamic no-leads ylag w64, C2 Schiff GBR no ylag w64, C3 GBM dynamic no-leads ylag w52, "
        "and C4 GBM dynamic no-leads ylag w40."
    ),
}
MODEL_INPUT_HISTORY_DIR = Path("data") / "model_input_history"
MODEL_INPUT_HISTORY_FILES = {
    "PED": "ped_inputs.parquet",
    "LIGHT_RUC": "light_ruc_inputs.parquet",
    "HEAVY_RUC": "heavy_ruc_inputs.parquet",
}
LIGHT_RUC_WINDOW = 36
LIGHT_RUC_BASE_FEATURES = [
    "log_real_diesel_price",
    "log_real_light_ruc_price",
    "log_lagged_real_light_ruc_price",
    "log_real_gdp",
    "post_2020_dummy",
    "q2_dummy",
    "q3_dummy",
    "q4_dummy",
]
LIGHT_RUC_RESIDUAL_FEATURES = [
    *LIGHT_RUC_BASE_FEATURES,
    "diesel_x_ruc_price",
    "gdp_x_post2020",
    "ruc_x_post2020",
    "diesel_x_post2020",
    "time_trend",
    "log_trend",
    "log_real_diesel_price_diff1",
    "log_real_diesel_price_lag1",
    "log_real_diesel_price_lag4",
    "log_real_light_ruc_price_diff1",
    "log_real_light_ruc_price_lag1",
    "log_real_light_ruc_price_lag4",
    "log_real_gdp_diff1",
    "log_real_gdp_lag1",
    "log_real_gdp_lag4",
]


@dataclass(frozen=True)
class TemplateColumn:
    name: str
    role: str
    required: bool
    description: str
    formula_key: str | None = None


COMMON_SYSTEM_COLUMNS = [
    TemplateColumn("period", "system", True, "Forecast quarter label generated by the template, for example 2026Q1."),
    TemplateColumn("year", "system", True, "Calendar year for the forecast quarter."),
    TemplateColumn("quarter", "system", True, "Calendar quarter number, 1 through 4."),
    TemplateColumn("horizon", "system", True, "Forecast horizon from the last known actual quarter."),
]

COMMON_FORMULA_COLUMNS = [
    TemplateColumn("q2_dummy", "formula", True, "1 when quarter is Q2, otherwise 0.", "q2_dummy"),
    TemplateColumn("q3_dummy", "formula", True, "1 when quarter is Q3, otherwise 0.", "q3_dummy"),
    TemplateColumn("q4_dummy", "formula", True, "1 when quarter is Q4, otherwise 0.", "q4_dummy"),
    TemplateColumn("post_2020_dummy", "formula", True, "1 for quarters after 2020, otherwise 0.", "post_2020_dummy"),
    TemplateColumn("trend_index", "formula", True, "Sequential time index used by static specifications.", "trend_index"),
]

PED_COLUMNS = [
    *COMMON_SYSTEM_COLUMNS,
    TemplateColumn("real_gdp_per_capita_nzd", "user", True, "User-entered real GDP per capita assumption."),
    TemplateColumn("population", "user", True, "User-entered population assumption."),
    TemplateColumn("unemployment_rate", "user", True, "User-entered unemployment rate assumption in percentage points."),
    TemplateColumn("real_petrol_price_cents_per_litre", "user", True, "User-entered real petrol price assumption."),
    TemplateColumn("target_lag_1", "user", True, "Most recent PED VKT per capita value available before this forecast quarter."),
    TemplateColumn("target_lag_4", "user", True, "PED VKT per capita value four quarters before this forecast quarter."),
    *COMMON_FORMULA_COLUMNS,
    TemplateColumn("log_real_gdp_per_capita", "formula", True, "Natural log of real GDP per capita.", "log_real_gdp_per_capita_nzd"),
    TemplateColumn("log_population", "formula", True, "Natural log of population.", "log_population"),
    TemplateColumn("log_unemployment_rate", "formula", True, "Natural log of unemployment rate.", "log_unemployment_rate"),
    TemplateColumn("log_real_petrol_price", "formula", True, "Natural log of real petrol price.", "log_real_petrol_price_cents_per_litre"),
    TemplateColumn("log_target_lag_1", "formula", True, "Natural log of target lag 1.", "log_target_lag_1"),
    TemplateColumn("log_target_lag_4", "formula", True, "Natural log of target lag 4.", "log_target_lag_4"),
    TemplateColumn("diff_log_target_lag_1_lag_4", "formula", True, "Log target lag 1 minus log target lag 4.", "diff_log_target"),
    TemplateColumn("gdp_petrol_interaction", "formula", True, "Log real GDP per capita multiplied by log real petrol price.", "gdp_petrol_interaction"),
    TemplateColumn("post_2011_x_log_trend", "formula", True, "Post-2011 dummy multiplied by log trend index.", "post_2011_x_log_trend"),
]

LIGHT_RUC_COLUMNS = [
    *COMMON_SYSTEM_COLUMNS,
    TemplateColumn("real_gdp_sa_nzd", "user", True, "User-entered real GDP assumption."),
    TemplateColumn("real_diesel_price_cents_per_litre", "user", True, "User-entered real diesel price assumption."),
    TemplateColumn("real_light_ruc_price_nzd_per_1000km", "user", True, "User-entered real Light RUC price assumption."),
    TemplateColumn("lagged_real_light_ruc_price_nzd_per_1000km", "user", True, "Real Light RUC price lag available before this forecast quarter."),
    TemplateColumn("target_lag_1", "user", True, "Most recent Light RUC volume available before this forecast quarter."),
    TemplateColumn("target_lag_4", "user", True, "Light RUC volume four quarters before this forecast quarter."),
    *COMMON_FORMULA_COLUMNS,
    TemplateColumn("log_real_gdp", "formula", True, "Natural log of real GDP.", "log_real_gdp_sa_nzd"),
    TemplateColumn("log_real_diesel_price", "formula", True, "Natural log of real diesel price.", "log_real_diesel_price_cents_per_litre"),
    TemplateColumn("log_real_light_ruc_price", "formula", True, "Natural log of real Light RUC price.", "log_real_light_ruc_price_nzd_per_1000km"),
    TemplateColumn("log_lagged_real_light_ruc_price", "formula", True, "Natural log of lagged real Light RUC price.", "log_lagged_real_light_ruc_price_nzd_per_1000km"),
    TemplateColumn("log_target_lag_1", "formula", True, "Natural log of target lag 1.", "log_target_lag_1"),
    TemplateColumn("log_target_lag_4", "formula", True, "Natural log of target lag 4.", "log_target_lag_4"),
    TemplateColumn("diff_log_real_gdp", "formula", True, "Quarterly difference in log real GDP.", "diff_log_real_gdp"),
    TemplateColumn("gdp_light_ruc_price_interaction", "formula", True, "Log real GDP multiplied by log real Light RUC price.", "gdp_light_ruc_price_interaction"),
]

HEAVY_RUC_COLUMNS = [
    *COMMON_SYSTEM_COLUMNS,
    TemplateColumn("real_gdp_sa_nzd", "user", True, "User-entered real GDP assumption."),
    TemplateColumn("real_diesel_price_cents_per_litre", "user", True, "User-entered real diesel price assumption."),
    TemplateColumn("unemployment_rate", "user", True, "User-entered unemployment rate assumption in percentage points."),
    TemplateColumn("real_light_ruc_price_nzd_per_1000km", "user", True, "User-entered real Light RUC price assumption used by Heavy components."),
    TemplateColumn("lagged_real_light_ruc_price_nzd_per_1000km", "user", True, "Real Light RUC price lag used by Heavy components."),
    TemplateColumn("real_heavy_ruc_price_nzd_per_1000km", "user", True, "User-entered real Heavy RUC price assumption."),
    TemplateColumn("lead_real_heavy_ruc_price_nzd_per_1000km", "user", True, "Expected next-quarter real Heavy RUC price assumption."),
    TemplateColumn("target_lag_1", "user", True, "Most recent Heavy RUC volume available before this forecast quarter."),
    TemplateColumn("target_lag_4", "user", True, "Heavy RUC volume four quarters before this forecast quarter."),
    *COMMON_FORMULA_COLUMNS,
    TemplateColumn("log_real_gdp", "formula", True, "Natural log of real GDP.", "log_real_gdp_sa_nzd"),
    TemplateColumn("log_real_diesel_price", "formula", True, "Natural log of real diesel price.", "log_real_diesel_price_cents_per_litre"),
    TemplateColumn("log_unemployment_rate", "formula", True, "Natural log of unemployment rate.", "log_unemployment_rate"),
    TemplateColumn("log_real_light_ruc_price", "formula", True, "Natural log of real Light RUC price.", "log_real_light_ruc_price_nzd_per_1000km"),
    TemplateColumn("log_lagged_real_light_ruc_price", "formula", True, "Natural log of lagged real Light RUC price.", "log_lagged_real_light_ruc_price_nzd_per_1000km"),
    TemplateColumn("log_real_heavy_ruc_price", "formula", True, "Natural log of real Heavy RUC price.", "log_real_heavy_ruc_price_nzd_per_1000km"),
    TemplateColumn("log_lead_real_heavy_ruc_price", "formula", True, "Natural log of lead real Heavy RUC price.", "log_lead_real_heavy_ruc_price_nzd_per_1000km"),
    TemplateColumn("log_target_lag_1", "formula", True, "Natural log of target lag 1.", "log_target_lag_1"),
    TemplateColumn("log_target_lag_4", "formula", True, "Natural log of target lag 4.", "log_target_lag_4"),
    TemplateColumn("diff_log_real_gdp", "formula", True, "Quarterly difference in log real GDP.", "diff_log_real_gdp"),
    TemplateColumn("gdp_heavy_ruc_price_interaction", "formula", True, "Log real GDP multiplied by log real Heavy RUC price.", "gdp_heavy_ruc_price_interaction"),
]

STREAM_COLUMNS = {
    "PED": PED_COLUMNS,
    "LIGHT_RUC": LIGHT_RUC_COLUMNS,
    "HEAVY_RUC": HEAVY_RUC_COLUMNS,
}


@dataclass
class ForecastValidationResult:
    valid: bool
    errors: list[str]
    warnings: list[str]
    assumptions: pd.DataFrame
    latest_actual_period: str
    forecast_periods: list[str]

    def report_frame(self) -> pd.DataFrame:
        rows = [
            {"severity": "error", "message": message}
            for message in self.errors
        ] + [
            {"severity": "warning", "message": message}
            for message in self.warnings
        ]
        if not rows:
            rows = [{"severity": "ok", "message": "Workbook inputs passed structural and required-value validation."}]
        return pd.DataFrame(rows)


@dataclass
class ForecastRunResult:
    output_dir: Path
    manifest: dict[str, Any]
    validation: ForecastValidationResult
    future_forecasts: pd.DataFrame
    component_forecasts: pd.DataFrame
    capability_report: pd.DataFrame
    assumptions: pd.DataFrame
    report_markdown: str

    @property
    def has_numeric_forecasts(self) -> bool:
        if self.future_forecasts.empty or "forecast" not in self.future_forecasts.columns:
            return False
        return pd.to_numeric(self.future_forecasts["forecast"], errors="coerce").notna().any()


def repo_root_from_here() -> Path:
    return Path(__file__).resolve().parents[1]


def latest_known_actual_period(repo_root: Path | str | None = None) -> str:
    root = Path(repo_root) if repo_root is not None else repo_root_from_here()
    candidates = [
        root / "data" / "dashboard_evidence_pack" / "data" / "scorecard_predictions.parquet",
        root / "data" / "dashboard_evidence_pack" / "data" / "component_predictions.parquet",
    ]
    periods: list[str] = []
    for path in candidates:
        if not path.exists():
            continue
        try:
            frame = pd.read_parquet(path, columns=["target_period"])
        except Exception:
            frame = pd.read_parquet(path)
        if "target_period" in frame.columns:
            periods.extend(frame["target_period"].dropna().astype(str).tolist())
    if not periods:
        return "2025Q4"
    return max(periods, key=quarter_sort_key)


def quarter_sort_key(period: str) -> int:
    year, quarter = parse_period(period)
    return year * 4 + quarter


def parse_period(period: str) -> tuple[int, int]:
    text = str(period).strip().upper()
    if "Q" not in text:
        raise ValueError(f"Invalid quarter period: {period!r}")
    year_text, quarter_text = text.split("Q", 1)
    year = int(year_text)
    quarter = int(quarter_text)
    if quarter not in {1, 2, 3, 4}:
        raise ValueError(f"Invalid quarter number in period: {period!r}")
    return year, quarter


def add_quarters(period: str, quarters: int) -> str:
    year, quarter = parse_period(period)
    index = year * 4 + (quarter - 1) + quarters
    return f"{index // 4}Q{(index % 4) + 1}"


def future_quarters_after(period: str, horizon: int = FORECAST_HORIZON_QUARTERS) -> list[str]:
    return [add_quarters(period, offset) for offset in range(1, horizon + 1)]


def build_forecast_input_template(
    output_path: Path | str,
    repo_root: Path | str | None = None,
) -> Path:
    root = Path(repo_root) if repo_root is not None else repo_root_from_here()
    latest = latest_known_actual_period(root)
    periods = future_quarters_after(latest)
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)

    wb = Workbook()
    readme = wb.active
    readme.title = "README"
    _write_readme_sheet(readme, latest, periods)
    for stream in STREAM_ORDER:
        ws = wb.create_sheet(SHEET_BY_STREAM[stream])
        _write_input_sheet(ws, stream, periods)
    wb.save(output)
    return output


def build_forecast_input_template_bytes(repo_root: Path | str | None = None) -> bytes:
    stream = BytesIO()
    root = Path(repo_root) if repo_root is not None else repo_root_from_here()
    latest = latest_known_actual_period(root)
    periods = future_quarters_after(latest)
    wb = Workbook()
    readme = wb.active
    readme.title = "README"
    _write_readme_sheet(readme, latest, periods)
    for stream_code in STREAM_ORDER:
        ws = wb.create_sheet(SHEET_BY_STREAM[stream_code])
        _write_input_sheet(ws, stream_code, periods)
    wb.save(stream)
    return stream.getvalue()


def _write_readme_sheet(ws: Any, latest_period: str, periods: list[str]) -> None:
    ws["A1"] = "NLTF 12-quarter forecast input template"
    ws["A1"].font = Font(bold=True, size=14, color="002B5C")
    rows = [
        ("Latest known actual quarter", latest_period),
        ("Forecast horizon", f"{periods[0]} to {periods[-1]}"),
        ("What to fill", "Only fill the user-entry columns in PED Inputs, Light RUC Inputs and Heavy RUC Inputs."),
        ("What not to edit", "Do not edit period, year, quarter, horizon or protected formula columns."),
        ("Data rule", "Use real price/GDP assumptions in the units named in each header."),
        ("Governance rule", "The runner does not run a broad candidate search and never overwrites dashboard evidence packs."),
        (
            "Missing model-state rule",
            "If repo-local fitted finalist artifacts are unavailable, the runner writes governed gaps instead of fake forecasts.",
        ),
    ]
    for row_index, (label, value) in enumerate(rows, start=3):
        ws.cell(row=row_index, column=1, value=label).font = Font(bold=True)
        ws.cell(row=row_index, column=2, value=value)
    ws.column_dimensions["A"].width = 32
    ws.column_dimensions["B"].width = 118
    ws.freeze_panes = "A3"


def _write_input_sheet(ws: Any, stream: str, periods: list[str]) -> None:
    columns = STREAM_COLUMNS[stream]
    header_fill = PatternFill("solid", fgColor="EAF2F8")
    user_fill = PatternFill("solid", fgColor="FFF7CC")
    formula_fill = PatternFill("solid", fgColor="E7F5EC")
    system_fill = PatternFill("solid", fgColor="E6EDF5")
    for col_index, column in enumerate(columns, start=1):
        cell = ws.cell(row=1, column=col_index, value=column.name)
        cell.font = Font(bold=True, color="002B5C")
        cell.fill = header_fill
        cell.comment = Comment(f"{column.role.upper()}: {column.description}", "Codex")
        ws.column_dimensions[get_column_letter(col_index)].width = max(15, min(34, len(column.name) + 3))

    col_map = {column.name: idx for idx, column in enumerate(columns, start=1)}
    for row_offset, period in enumerate(periods, start=2):
        year, quarter = parse_period(period)
        system_values = {
            "period": period,
            "year": year,
            "quarter": quarter,
            "horizon": row_offset - 1,
        }
        for column in columns:
            cell = ws.cell(row=row_offset, column=col_map[column.name])
            if column.role == "system":
                cell.value = system_values[column.name]
                cell.fill = system_fill
            elif column.role == "formula":
                cell.value = _excel_formula(column.formula_key or column.name, row_offset, col_map)
                cell.fill = formula_fill
            else:
                cell.fill = user_fill
                cell.protection = Protection(locked=False)
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = ws.dimensions
    ws.protection.sheet = True
    ws.protection.enable()


def _cell(row: int, col_map: dict[str, int], column: str) -> str:
    return f"{get_column_letter(col_map[column])}{row}"


def _excel_formula(formula_key: str, row: int, col_map: dict[str, int]) -> str:
    q = _cell(row, col_map, "quarter")
    year = _cell(row, col_map, "year")
    horizon = _cell(row, col_map, "horizon")
    if formula_key == "q2_dummy":
        return f'=IF({q}=2,1,0)'
    if formula_key == "q3_dummy":
        return f'=IF({q}=3,1,0)'
    if formula_key == "q4_dummy":
        return f'=IF({q}=4,1,0)'
    if formula_key == "post_2020_dummy":
        return f'=IF({year}>=2021,1,0)'
    if formula_key == "trend_index":
        return f"={horizon}+104"
    if formula_key == "diff_log_real_gdp":
        current = _cell(row, col_map, "log_real_gdp")
        if row == 2:
            return '=""'
        previous = _cell(row - 1, col_map, "log_real_gdp")
        return f'=IF(AND({current}<>"",{previous}<>""),{current}-{previous},"")'
    if formula_key == "diff_log_target":
        lag1 = _cell(row, col_map, "log_target_lag_1")
        lag4 = _cell(row, col_map, "log_target_lag_4")
        return f'=IF(AND({lag1}<>"",{lag4}<>""),{lag1}-{lag4},"")'
    if formula_key == "gdp_petrol_interaction":
        gdp = _cell(row, col_map, "log_real_gdp_per_capita")
        price = _cell(row, col_map, "log_real_petrol_price")
        return f'=IF(AND({gdp}<>"",{price}<>""),{gdp}*{price},"")'
    if formula_key == "gdp_light_ruc_price_interaction":
        gdp = _cell(row, col_map, "log_real_gdp")
        price = _cell(row, col_map, "log_real_light_ruc_price")
        return f'=IF(AND({gdp}<>"",{price}<>""),{gdp}*{price},"")'
    if formula_key == "gdp_heavy_ruc_price_interaction":
        gdp = _cell(row, col_map, "log_real_gdp")
        price = _cell(row, col_map, "log_real_heavy_ruc_price")
        return f'=IF(AND({gdp}<>"",{price}<>""),{gdp}*{price},"")'
    if formula_key == "post_2011_x_log_trend":
        trend = _cell(row, col_map, "trend_index")
        return f'=IF({trend}>0,LN({trend}),"")'
    if formula_key.startswith("log_"):
        source = formula_key.removeprefix("log_")
        source_cell = _cell(row, col_map, source)
        return f'=IF({source_cell}>0,LN({source_cell}),"")'
    return '=""'


def validate_forecast_workbook(
    workbook: Path | str | bytes | BinaryIO,
    repo_root: Path | str | None = None,
) -> ForecastValidationResult:
    root = Path(repo_root) if repo_root is not None else repo_root_from_here()
    latest = latest_known_actual_period(root)
    periods = future_quarters_after(latest)
    errors: list[str] = []
    warnings: list[str] = []
    frames: list[pd.DataFrame] = []
    try:
        wb = _load_workbook_from_input(workbook)
    except Exception as exc:
        return ForecastValidationResult(False, [f"Workbook could not be opened: {exc}"], [], pd.DataFrame(), latest, periods)

    for stream in STREAM_ORDER:
        sheet = SHEET_BY_STREAM[stream]
        if sheet not in wb.sheetnames:
            errors.append(f"Missing required sheet: {sheet}")
            continue
        frame = _worksheet_to_frame(wb[sheet])
        sheet_errors, sheet_warnings = _validate_sheet_frame(frame, stream, periods)
        errors.extend(sheet_errors)
        warnings.extend(sheet_warnings)
        if not frame.empty:
            frames.append(_build_stream_assumptions(frame, stream, periods))

    assumptions = pd.concat(frames, ignore_index=True, sort=False) if frames else pd.DataFrame()
    return ForecastValidationResult(not errors, errors, warnings, assumptions, latest, periods)


def run_forecast_workbook(
    workbook: Path | str | bytes | BinaryIO,
    output_dir: Path | str | None = None,
    repo_root: Path | str | None = None,
    workbook_filename: str | None = None,
    run_timestamp: str | None = None,
) -> ForecastRunResult:
    root = Path(repo_root) if repo_root is not None else repo_root_from_here()
    validation = validate_forecast_workbook(workbook, root)
    timestamp = run_timestamp or datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    run_dir = Path(output_dir) if output_dir is not None else root / "artifacts" / "forecast_runs" / timestamp
    run_dir.mkdir(parents=True, exist_ok=True)
    workbook_bytes = _workbook_bytes(workbook)
    workbook_hash = hashlib.sha256(workbook_bytes).hexdigest() if workbook_bytes else None

    capabilities = model_capability_gap_register(root)
    future, components = _forecast_output_rows(validation, capabilities, root)
    capability_report = _forecast_capability_report(capabilities, future, components, validation)
    assumptions = validation.assumptions.copy()
    report = _forecast_validation_report(validation, capabilities)
    forecast_status = _forecast_status(validation, future)
    manifest = {
        "run_id": timestamp,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "forecast_runner_version": FORECAST_RUNNER_VERSION,
        "workbook_filename": workbook_filename or _workbook_name(workbook),
        "workbook_sha256": workbook_hash,
        "latest_actual_period": validation.latest_actual_period,
        "forecast_periods": validation.forecast_periods,
        "validation_status": "passed" if validation.valid else "failed",
        "validation_errors": validation.errors,
        "validation_warnings": validation.warnings,
        "fixed_finalists_only": True,
        "broad_search_run": False,
        "evidence_pack_modified": False,
        "chart_sources_modified": False,
        "forecast_status": forecast_status,
        "numeric_forecast_streams": sorted(
            future.loc[future["forecast_available"].fillna(False).astype(bool), "stream"].dropna().astype(str).unique().tolist()
        ),
        "governed_gap_streams": sorted(
            future.loc[~future["forecast_available"].fillna(False).astype(bool), "stream"].dropna().astype(str).unique().tolist()
        ),
        "model_capabilities": _json_safe_records(capabilities),
        "output_files": [
            "future_forecasts.parquet",
            "component_forecasts.parquet",
            "forecast_assumptions.parquet",
            "forecast_capability_report.parquet",
            "forecast_run_manifest.json",
            "forecast_validation_report.md",
            "future_forecasts.csv",
            "component_forecasts.csv",
            "forecast_assumptions.csv",
            "forecast_capability_report.csv",
        ],
    }

    future.to_parquet(run_dir / "future_forecasts.parquet", index=False)
    components.to_parquet(run_dir / "component_forecasts.parquet", index=False)
    assumptions.to_parquet(run_dir / "forecast_assumptions.parquet", index=False)
    capability_report.to_parquet(run_dir / "forecast_capability_report.parquet", index=False)
    future.to_csv(run_dir / "future_forecasts.csv", index=False)
    components.to_csv(run_dir / "component_forecasts.csv", index=False)
    assumptions.to_csv(run_dir / "forecast_assumptions.csv", index=False)
    capability_report.to_csv(run_dir / "forecast_capability_report.csv", index=False)
    (run_dir / "forecast_run_manifest.json").write_text(json.dumps(manifest, indent=2, allow_nan=False), encoding="utf-8")
    (run_dir / "forecast_validation_report.md").write_text(report, encoding="utf-8")

    return ForecastRunResult(
        output_dir=run_dir,
        manifest=manifest,
        validation=validation,
        future_forecasts=future,
        component_forecasts=components,
        capability_report=capability_report,
        assumptions=assumptions,
        report_markdown=report,
    )


def forecast_pack_zip_bytes(output_dir: Path | str) -> bytes:
    root = Path(output_dir)
    stream = BytesIO()
    with zipfile.ZipFile(stream, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for path in sorted(root.glob("*")):
            if path.is_file():
                zf.write(path, arcname=path.name)
    return stream.getvalue()


def create_completed_sample_workbook(
    output_path: Path | str,
    repo_root: Path | str | None = None,
) -> Path:
    path = build_forecast_input_template(output_path, repo_root=repo_root)
    wb = load_workbook(path)
    sample_values = {
        "real_gdp_per_capita_nzd": 72000.0,
        "population": 5300000.0,
        "unemployment_rate": 4.2,
        "real_petrol_price_cents_per_litre": 265.0,
        "real_gdp_sa_nzd": 320000000000.0,
        "real_diesel_price_cents_per_litre": 232.0,
        "real_light_ruc_price_nzd_per_1000km": 84.0,
        "lagged_real_light_ruc_price_nzd_per_1000km": 82.0,
        "real_heavy_ruc_price_nzd_per_1000km": 188.0,
        "lead_real_heavy_ruc_price_nzd_per_1000km": 190.0,
        "target_lag_1": 1000.0,
        "target_lag_4": 980.0,
    }
    for stream in STREAM_ORDER:
        ws = wb[SHEET_BY_STREAM[stream]]
        headers = {cell.value: cell.column for cell in ws[1] if cell.value}
        ws.protection.sheet = False
        for row in range(2, 2 + FORECAST_HORIZON_QUARTERS):
            for name, value in sample_values.items():
                if name in headers:
                    multiplier = 1.0 + ((row - 2) * 0.004)
                    ws.cell(row=row, column=headers[name], value=value * multiplier)
        ws.protection.sheet = True
    wb.save(path)
    return path


def model_capability_gap_register(repo_root: Path | str | None = None) -> pd.DataFrame:
    root = Path(repo_root) if repo_root is not None else repo_root_from_here()
    rows: list[dict[str, Any]] = []
    for stream in STREAM_ORDER:
        available, gap_code, gap_reason, artifact_basis = _stream_forward_capability(root, stream)
        rows.append(
            {
                "stream": stream,
                "stream_label": STREAM_LABELS[stream],
                "model": FINALIST_BY_STREAM[stream],
                "forecast_capability_available": available,
                "capability_status": "numeric_forecast_available" if available else "governed_gap",
                "gap_code": gap_code,
                "gap_reason": gap_reason,
                "repo_artifact_basis": artifact_basis,
                "required_for_forward_forecast": True,
            }
        )
    return pd.DataFrame(rows)


def _stream_forward_capability(root: Path, stream: str) -> tuple[bool, str | None, str, str]:
    history = root / MODEL_INPUT_HISTORY_DIR / MODEL_INPUT_HISTORY_FILES[stream]
    manifest = root / MODEL_INPUT_HISTORY_DIR / "manifest.json"
    if stream == "LIGHT_RUC":
        registry = root / "data" / "dashboard_evidence_pack_reproducibility" / "light_ruc" / "model_registry.parquet"
        missing = [path for path in [history, manifest, registry] if not path.exists()]
        sklearn_error = _sklearn_import_error()
        if not missing and sklearn_error is None:
            basis = "; ".join(
                [
                    _repo_relative(root, history),
                    _repo_relative(root, manifest),
                    _repo_relative(root, registry),
                    "requirements.txt::scikit-learn",
                ]
            )
            return True, None, "", basis
        reason_parts: list[str] = []
        if missing:
            reason_parts.append("missing repo-local artifacts: " + ", ".join(_repo_relative(root, path) for path in missing))
        if sklearn_error is not None:
            reason_parts.append(f"scikit-learn runtime unavailable: {sklearn_error}")
        return (
            False,
            MISSING_CAPABILITY_BY_STREAM[stream],
            MISSING_CAPABILITY_NOTES[stream] + " " + "; ".join(reason_parts),
            _capability_basis(root, stream),
        )
    return False, MISSING_CAPABILITY_BY_STREAM[stream], MISSING_CAPABILITY_NOTES[stream], _capability_basis(root, stream)


def _sklearn_import_error() -> str | None:
    try:
        import sklearn  # noqa: F401
    except Exception as exc:
        return f"{type(exc).__name__}: {exc}"
    return None


def _capability_basis(root: Path, stream: str) -> str:
    paths = [
        root / "data" / "dashboard_evidence_pack" / "data" / "model_registry.parquet",
        root / "data" / "dashboard_evidence_pack" / "data" / "model_coefficients.parquet",
        root / MODEL_INPUT_HISTORY_DIR / MODEL_INPUT_HISTORY_FILES[stream],
        root / MODEL_INPUT_HISTORY_DIR / "manifest.json",
    ]
    if stream == "PED":
        paths.append(root / "data" / "dashboard_evidence_pack_reproducibility" / "ped_inner_hpo" / "model_coefficients.parquet")
    if stream == "LIGHT_RUC":
        paths.append(root / "data" / "dashboard_evidence_pack_reproducibility" / "light_ruc" / "model_coefficients.parquet")
    if stream == "HEAVY_RUC":
        paths.append(root / "data" / "dashboard_evidence_pack_reproducibility" / "heavy_ruc" / "model_coefficients.parquet")
    return "; ".join(_repo_relative(root, path) for path in paths if path.exists())


def _load_workbook_from_input(workbook: Path | str | bytes | BinaryIO) -> Any:
    if isinstance(workbook, bytes):
        return load_workbook(BytesIO(workbook), data_only=False)
    if hasattr(workbook, "read"):
        content = workbook.read()
        if hasattr(workbook, "seek"):
            workbook.seek(0)
        return load_workbook(BytesIO(content), data_only=False)
    return load_workbook(Path(workbook), data_only=False)


def _workbook_bytes(workbook: Path | str | bytes | BinaryIO) -> bytes:
    if isinstance(workbook, bytes):
        return workbook
    if hasattr(workbook, "read"):
        content = workbook.read()
        if hasattr(workbook, "seek"):
            workbook.seek(0)
        return content
    path = Path(workbook)
    return path.read_bytes() if path.exists() else b""


def _workbook_name(workbook: Path | str | bytes | BinaryIO) -> str:
    if isinstance(workbook, (str, Path)):
        return Path(workbook).name
    return getattr(workbook, "name", "uploaded_forecast_workbook.xlsx")


def _worksheet_to_frame(ws: Any) -> pd.DataFrame:
    headers = [str(cell.value).strip() if cell.value is not None else "" for cell in ws[1]]
    rows: list[dict[str, Any]] = []
    for row in ws.iter_rows(min_row=2, values_only=True):
        if not any(value is not None for value in row):
            continue
        rows.append({header: value for header, value in zip(headers, row, strict=False) if header})
    return pd.DataFrame(rows)


def _validate_sheet_frame(frame: pd.DataFrame, stream: str, periods: list[str]) -> tuple[list[str], list[str]]:
    errors: list[str] = []
    warnings: list[str] = []
    sheet = SHEET_BY_STREAM[stream]
    expected_headers = [column.name for column in STREAM_COLUMNS[stream]]
    missing_headers = [name for name in expected_headers if name not in frame.columns]
    if missing_headers:
        errors.append(f"{sheet}: missing required headers: {', '.join(missing_headers)}")
        return errors, warnings
    if len(frame) != FORECAST_HORIZON_QUARTERS:
        errors.append(f"{sheet}: expected {FORECAST_HORIZON_QUARTERS} forecast rows, found {len(frame)}")
    observed_periods = frame["period"].dropna().astype(str).str.upper().tolist()
    if observed_periods[:FORECAST_HORIZON_QUARTERS] != periods:
        errors.append(f"{sheet}: period rows must be {periods[0]} through {periods[-1]} with no gaps")
    for column in [col for col in STREAM_COLUMNS[stream] if col.role == "user" and col.required]:
        values = pd.to_numeric(frame[column.name], errors="coerce") if column.name in frame.columns else pd.Series(dtype=float)
        if values.isna().any():
            errors.append(f"{sheet}: required user-entry column {column.name} has missing or non-numeric values")
        elif (values <= 0).any():
            errors.append(f"{sheet}: required user-entry column {column.name} must be positive for log/lag transforms")
    formula_headers = [col.name for col in STREAM_COLUMNS[stream] if col.role == "formula"]
    if not formula_headers:
        warnings.append(f"{sheet}: no formula columns were found")
    return errors, warnings


def _build_stream_assumptions(frame: pd.DataFrame, stream: str, periods: list[str]) -> pd.DataFrame:
    out = frame.copy()
    out = out.head(FORECAST_HORIZON_QUARTERS).copy()
    out["stream"] = stream
    out["stream_label"] = STREAM_LABELS[stream]
    out["model"] = FINALIST_BY_STREAM[stream]
    out["period"] = periods[: len(out)]
    out["year"] = out["period"].map(lambda value: parse_period(value)[0])
    out["quarter"] = out["period"].map(lambda value: parse_period(value)[1])
    out["horizon"] = range(1, len(out) + 1)
    q = pd.to_numeric(out["quarter"], errors="coerce")
    out["q2_dummy"] = q.eq(2).astype(int)
    out["q3_dummy"] = q.eq(3).astype(int)
    out["q4_dummy"] = q.eq(4).astype(int)
    out["post_2020_dummy"] = pd.to_numeric(out["year"], errors="coerce").ge(2021).astype(int)
    out["trend_index"] = out["period"].map(lambda value: quarter_sort_key(value) - quarter_sort_key("2000Q1") + 1)

    for source in [
        "real_gdp_sa_nzd",
        "real_gdp_per_capita_nzd",
        "population",
        "unemployment_rate",
        "real_petrol_price_cents_per_litre",
        "real_diesel_price_cents_per_litre",
        "real_light_ruc_price_nzd_per_1000km",
        "lagged_real_light_ruc_price_nzd_per_1000km",
        "real_heavy_ruc_price_nzd_per_1000km",
        "lead_real_heavy_ruc_price_nzd_per_1000km",
        "target_lag_1",
        "target_lag_4",
    ]:
        if source in out.columns:
            numeric = pd.to_numeric(out[source], errors="coerce")
            out[source] = numeric
            out[f"log_{source}"] = np.where(numeric > 0, np.log(numeric), np.nan)

    if "log_real_gdp_sa_nzd" in out.columns:
        out["diff_log_real_gdp"] = out["log_real_gdp_sa_nzd"].diff()
        out["log_real_gdp"] = out["log_real_gdp_sa_nzd"]
    if "log_real_gdp_per_capita_nzd" in out.columns:
        out["log_real_gdp_per_capita"] = out["log_real_gdp_per_capita_nzd"]
    if "log_real_petrol_price_cents_per_litre" in out.columns:
        out["log_real_petrol_price"] = out["log_real_petrol_price_cents_per_litre"]
    if "log_real_diesel_price_cents_per_litre" in out.columns:
        out["log_real_diesel_price"] = out["log_real_diesel_price_cents_per_litre"]
    if "log_real_light_ruc_price_nzd_per_1000km" in out.columns:
        out["log_real_light_ruc_price"] = out["log_real_light_ruc_price_nzd_per_1000km"]
    if "log_lagged_real_light_ruc_price_nzd_per_1000km" in out.columns:
        out["log_lagged_real_light_ruc_price"] = out["log_lagged_real_light_ruc_price_nzd_per_1000km"]
    if "log_real_heavy_ruc_price_nzd_per_1000km" in out.columns:
        out["log_real_heavy_ruc_price"] = out["log_real_heavy_ruc_price_nzd_per_1000km"]
    if "log_lead_real_heavy_ruc_price_nzd_per_1000km" in out.columns:
        out["log_lead_real_heavy_ruc_price"] = out["log_lead_real_heavy_ruc_price_nzd_per_1000km"]
    if {"log_target_lag_1", "log_target_lag_4"}.issubset(out.columns):
        out["diff_log_target_lag_1_lag_4"] = out["log_target_lag_1"] - out["log_target_lag_4"]
    if {"log_real_gdp_per_capita", "log_real_petrol_price"}.issubset(out.columns):
        out["gdp_petrol_interaction"] = out["log_real_gdp_per_capita"] * out["log_real_petrol_price"]
    if {"log_real_gdp", "log_real_light_ruc_price"}.issubset(out.columns):
        out["gdp_light_ruc_price_interaction"] = out["log_real_gdp"] * out["log_real_light_ruc_price"]
    if {"log_real_gdp", "log_real_heavy_ruc_price"}.issubset(out.columns):
        out["gdp_heavy_ruc_price_interaction"] = out["log_real_gdp"] * out["log_real_heavy_ruc_price"]
    out["post_2011_x_log_trend"] = np.where(out["trend_index"] > 0, np.log(out["trend_index"]), np.nan)
    out["transform_status"] = "built_from_template_inputs"
    return out


def _forecast_output_rows(
    validation: ForecastValidationResult,
    capabilities: pd.DataFrame,
    repo_root: Path,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    light_future: pd.DataFrame | None = None
    light_components: pd.DataFrame | None = None
    light_error: str | None = None
    cap_lookup = capabilities.set_index("stream").to_dict(orient="index")
    if validation.valid and cap_lookup.get("LIGHT_RUC", {}).get("forecast_capability_available"):
        try:
            light_future, light_components = _light_ruc_forward_forecast(validation, repo_root)
        except Exception as exc:
            light_error = f"{type(exc).__name__}: {exc}"

    future_rows: list[pd.DataFrame] = []
    component_rows: list[pd.DataFrame] = []
    for stream in STREAM_ORDER:
        if stream == "LIGHT_RUC" and light_future is not None and light_components is not None:
            future_rows.append(light_future)
            component_rows.append(light_components)
            continue
        error_suffix = f" Scorer error: {light_error}" if stream == "LIGHT_RUC" and light_error else ""
        future_rows.append(_gap_future_forecast_rows(validation, capabilities, stream, error_suffix=error_suffix))
        component_rows.append(_gap_component_forecast_rows(validation, capabilities, repo_root, stream, error_suffix=error_suffix))
    future = pd.concat(future_rows, ignore_index=True, sort=False) if future_rows else pd.DataFrame()
    components = pd.concat(component_rows, ignore_index=True, sort=False) if component_rows else pd.DataFrame()
    return future, components


def _gap_future_forecast_rows(
    validation: ForecastValidationResult,
    capabilities: pd.DataFrame,
    stream: str,
    *,
    error_suffix: str = "",
) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    cap_lookup = capabilities.set_index("stream").to_dict(orient="index")
    cap = cap_lookup[stream]
    for horizon, period in enumerate(validation.forecast_periods, start=1):
        rows.append(
            {
                "stream": stream,
                "stream_label": STREAM_LABELS[stream],
                "model": FINALIST_BY_STREAM[stream],
                "target_period": period,
                "horizon": horizon,
                "forecast": pd.NA,
                "prediction": pd.NA,
                "forecast_available": False,
                "availability_status": "validation_failed" if not validation.valid else "governed_gap",
                "gap_code": "input_validation_failed" if not validation.valid else cap["gap_code"],
                "gap_reason": "; ".join(validation.errors) if not validation.valid else str(cap["gap_reason"]) + error_suffix,
                "fixed_finalist_only": True,
                "broad_search_run": False,
            }
        )
    return pd.DataFrame(rows)


def _gap_component_forecast_rows(
    validation: ForecastValidationResult,
    capabilities: pd.DataFrame,
    repo_root: Path,
    stream: str,
    *,
    error_suffix: str = "",
) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    cap_lookup = capabilities.set_index("stream").to_dict(orient="index")
    components = _component_registry(repo_root)
    cap = cap_lookup[stream]
    stream_components = components.get(stream, [])
    for horizon, period in enumerate(validation.forecast_periods, start=1):
        for component in stream_components:
            rows.append(
                {
                    "stream": stream,
                    "stream_label": STREAM_LABELS[stream],
                    "model": FINALIST_BY_STREAM[stream],
                    "component_model": component.get("component_model"),
                    "component_role": component.get("component_role"),
                    "component_weight": component.get("component_weight"),
                    "target_period": period,
                    "horizon": horizon,
                    "component_forecast": pd.NA,
                    "component_log_value": pd.NA,
                    "weighted_component_forecast": pd.NA,
                    "forecast_available": False,
                    "availability_status": "validation_failed" if not validation.valid else "governed_gap",
                    "gap_code": "input_validation_failed" if not validation.valid else cap["gap_code"],
                    "gap_reason": "; ".join(validation.errors) if not validation.valid else str(cap["gap_reason"]) + error_suffix,
                    "fixed_finalist_only": True,
                    "broad_search_run": False,
                }
            )
    return pd.DataFrame(rows)


def _light_ruc_forward_forecast(validation: ForecastValidationResult, repo_root: Path) -> tuple[pd.DataFrame, pd.DataFrame]:
    from sklearn.ensemble import GradientBoostingRegressor

    history_path = repo_root / MODEL_INPUT_HISTORY_DIR / MODEL_INPUT_HISTORY_FILES["LIGHT_RUC"]
    history = pd.read_parquet(history_path)
    future = validation.assumptions[validation.assumptions["stream"].astype(str).eq("LIGHT_RUC")].copy()
    if future.empty:
        raise ValueError("Light RUC future assumption rows are missing from the validated workbook.")

    feature_frame = _light_ruc_feature_frame(history, future, validation.latest_actual_period)
    train = feature_frame[feature_frame["sample_scope"].eq("history")].copy()
    train = train[train["period_key"].le(quarter_sort_key(validation.latest_actual_period))].copy()
    train["target"] = pd.to_numeric(train["target"], errors="coerce")
    required = ["target", *LIGHT_RUC_BASE_FEATURES, *LIGHT_RUC_RESIDUAL_FEATURES]
    train = train.replace([np.inf, -np.inf], np.nan).dropna(subset=required)
    train = train[train["target"].gt(0)].sort_values("period_key").tail(LIGHT_RUC_WINDOW).copy()
    if len(train) < LIGHT_RUC_WINDOW:
        raise ValueError(f"Light RUC scorer requires {LIGHT_RUC_WINDOW} usable training rows; found {len(train)}.")

    future_features = feature_frame[feature_frame["sample_scope"].eq("future")].copy()
    future_features = future_features.replace([np.inf, -np.inf], np.nan)
    missing_future = _missing_feature_columns(future_features, LIGHT_RUC_RESIDUAL_FEATURES)
    if missing_future:
        raise ValueError("Light RUC future rows are missing required residual features: " + ", ".join(missing_future))

    y = np.log(train["target"].to_numpy(dtype=float))
    base_x = train[LIGHT_RUC_BASE_FEATURES].to_numpy(dtype=float)
    beta = _ols_fit(base_x, y)
    train_base_log = _ols_predict(base_x, beta)
    residual_target = y - train_base_log
    residual_model = GradientBoostingRegressor(
        n_estimators=150,
        max_depth=1,
        learning_rate=0.05,
        subsample=0.85,
        random_state=42,
        loss="squared_error",
    )
    residual_model.fit(train[LIGHT_RUC_RESIDUAL_FEATURES].to_numpy(dtype=float), residual_target)

    future_base_log = _ols_predict(future_features[LIGHT_RUC_BASE_FEATURES].to_numpy(dtype=float), beta)
    future_residual_log = residual_model.predict(future_features[LIGHT_RUC_RESIDUAL_FEATURES].to_numpy(dtype=float))
    final_log = future_base_log + future_residual_log
    forecast = np.exp(final_log)

    future_rows: list[dict[str, Any]] = []
    component_rows: list[dict[str, Any]] = []
    train_start = str(train.iloc[0]["period"])
    train_end = str(train.iloc[-1]["period"])
    for idx, (_, row) in enumerate(future_features.sort_values("horizon").iterrows()):
        horizon = int(row["horizon"])
        period = str(row["period"])
        base_log = float(future_base_log[idx])
        residual_log = float(future_residual_log[idx])
        final_log_value = float(final_log[idx])
        final_prediction = float(forecast[idx])
        base_prediction = float(np.exp(base_log))
        residual_multiplier = float(np.exp(residual_log))
        common = {
            "stream": "LIGHT_RUC",
            "stream_label": STREAM_LABELS["LIGHT_RUC"],
            "model": FINALIST_BY_STREAM["LIGHT_RUC"],
            "target_period": period,
            "horizon": horizon,
            "availability_status": "numeric_forecast_available",
            "gap_code": None,
            "gap_reason": "",
            "fixed_finalist_only": True,
            "broad_search_run": False,
            "source_recipe": "Schiff-style OLS base plus GradientBoostingRegressor residual correction",
            "training_window_start": train_start,
            "training_window_end": train_end,
            "training_window_rows": len(train),
            "score_basis": "forward_assumption_workbook",
        }
        future_rows.append(
            {
                **common,
                "forecast": final_prediction,
                "prediction": final_prediction,
                "forecast_available": True,
                "base_forecast": base_prediction,
                "residual_log_correction": residual_log,
                "residual_multiplier": residual_multiplier,
                "final_log_forecast": final_log_value,
            }
        )
        component_rows.extend(
            [
                {
                    **common,
                    "component_model": "base_schiff_ols",
                    "component_role": "OLS base level prediction",
                    "component_weight": pd.NA,
                    "component_forecast": base_prediction,
                    "component_log_value": base_log,
                    "weighted_component_forecast": pd.NA,
                    "forecast_available": True,
                },
                {
                    **common,
                    "component_model": "residual_gbr",
                    "component_role": "GBM residual log-correction multiplier",
                    "component_weight": pd.NA,
                    "component_forecast": residual_multiplier,
                    "component_log_value": residual_log,
                    "weighted_component_forecast": pd.NA,
                    "forecast_available": True,
                },
                {
                    **common,
                    "component_model": FINALIST_BY_STREAM["LIGHT_RUC"],
                    "component_role": "final level prediction",
                    "component_weight": 1.0,
                    "component_forecast": final_prediction,
                    "component_log_value": final_log_value,
                    "weighted_component_forecast": final_prediction,
                    "forecast_available": True,
                },
            ]
        )
    return pd.DataFrame(future_rows), pd.DataFrame(component_rows)


def _light_ruc_feature_frame(history: pd.DataFrame, future: pd.DataFrame, latest_actual_period: str) -> pd.DataFrame:
    history_cols = [
        "period",
        "year",
        "quarter",
        "target",
        "real_gdp_sa_nzd",
        "real_diesel_price_cents_per_litre",
        "real_light_ruc_price_nzd_per_1000km",
        "lagged_real_light_ruc_price_nzd_per_1000km",
        "log_real_gdp",
        "log_real_diesel_price",
        "log_real_light_ruc_price",
        "log_lagged_real_light_ruc_price",
        "q2_dummy",
        "q3_dummy",
        "q4_dummy",
        "post_2020_dummy",
    ]
    hist = history[[column for column in history_cols if column in history.columns]].copy()
    hist["sample_scope"] = "history"
    hist["horizon"] = pd.NA
    fut = future.copy()
    fut["sample_scope"] = "future"
    fut["target"] = pd.NA
    combined = pd.concat([hist, fut], ignore_index=True, sort=False)
    combined["period"] = combined["period"].astype(str).str.upper()
    combined["period_key"] = combined["period"].map(quarter_sort_key)
    combined = combined.sort_values("period_key").reset_index(drop=True)
    first_history_key = combined.loc[combined["sample_scope"].eq("history"), "period_key"].min()
    combined["period_index"] = combined["period_key"] - int(first_history_key) + 1
    combined["time_trend"] = combined["period_index"]
    combined["log_trend"] = np.where(combined["time_trend"] > 0, np.log(combined["time_trend"]), np.nan)
    combined["year"] = combined["period"].map(lambda value: parse_period(value)[0])
    combined["quarter"] = combined["period"].map(lambda value: parse_period(value)[1])
    q = pd.to_numeric(combined["quarter"], errors="coerce")
    combined["q2_dummy"] = q.eq(2).astype(int)
    combined["q3_dummy"] = q.eq(3).astype(int)
    combined["q4_dummy"] = q.eq(4).astype(int)
    combined["post_2020_dummy"] = pd.to_numeric(combined["year"], errors="coerce").ge(2021).astype(int)
    _ensure_log_column(combined, "real_gdp_sa_nzd", "log_real_gdp")
    _ensure_log_column(combined, "real_diesel_price_cents_per_litre", "log_real_diesel_price")
    _ensure_log_column(combined, "real_light_ruc_price_nzd_per_1000km", "log_real_light_ruc_price")
    _ensure_log_column(combined, "lagged_real_light_ruc_price_nzd_per_1000km", "log_lagged_real_light_ruc_price")
    log_diesel = pd.to_numeric(combined["log_real_diesel_price"], errors="coerce")
    log_ruc = pd.to_numeric(combined["log_real_light_ruc_price"], errors="coerce")
    log_gdp = pd.to_numeric(combined["log_real_gdp"], errors="coerce")
    post = pd.to_numeric(combined["post_2020_dummy"], errors="coerce").fillna(0)
    combined["diesel_x_ruc_price"] = log_diesel * log_ruc
    combined["gdp_x_post2020"] = log_gdp * post
    combined["ruc_x_post2020"] = log_ruc * post
    combined["diesel_x_post2020"] = log_diesel * post
    combined["log_real_diesel_price_diff1"] = log_diesel.diff()
    combined["log_real_diesel_price_lag1"] = log_diesel.shift(1)
    combined["log_real_diesel_price_lag4"] = log_diesel.shift(4)
    combined["log_real_light_ruc_price_diff1"] = log_ruc.diff()
    combined["log_real_light_ruc_price_lag1"] = log_ruc.shift(1)
    combined["log_real_light_ruc_price_lag4"] = log_ruc.shift(4)
    combined["log_real_gdp_diff1"] = log_gdp.diff()
    combined["log_real_gdp_lag1"] = log_gdp.shift(1)
    combined["log_real_gdp_lag4"] = log_gdp.shift(4)
    combined.loc[combined["period_key"].gt(quarter_sort_key(latest_actual_period)) & combined["sample_scope"].eq("history"), "sample_scope"] = (
        "future_placeholder"
    )
    return combined


def _ensure_log_column(frame: pd.DataFrame, source: str, target: str) -> None:
    if target in frame.columns and pd.to_numeric(frame[target], errors="coerce").notna().any():
        frame[target] = pd.to_numeric(frame[target], errors="coerce")
        return
    numeric = pd.to_numeric(frame.get(source), errors="coerce")
    frame[target] = np.where(numeric > 0, np.log(numeric), np.nan)


def _missing_feature_columns(frame: pd.DataFrame, columns: list[str]) -> list[str]:
    missing: list[str] = []
    for column in columns:
        if column not in frame.columns or pd.to_numeric(frame[column], errors="coerce").isna().any():
            missing.append(column)
    return missing


def _ols_fit(features: np.ndarray, target: np.ndarray) -> np.ndarray:
    design = np.column_stack([np.ones(len(features)), features])
    return np.linalg.lstsq(design, target, rcond=None)[0]


def _ols_predict(features: np.ndarray, beta: np.ndarray) -> np.ndarray:
    design = np.column_stack([np.ones(len(features)), features])
    return design @ beta


def _component_registry(repo_root: Path) -> dict[str, list[dict[str, Any]]]:
    heavy_components: list[dict[str, Any]] = []
    heavy_path = repo_root / "data" / "dashboard_evidence_pack" / "data" / "ensemble_components.parquet"
    if heavy_path.exists():
        try:
            heavy = pd.read_parquet(heavy_path)
            heavy = heavy[heavy["stream"].astype(str).eq("HEAVY_RUC")]
            for _, row in heavy.iterrows():
                heavy_components.append(
                    {
                        "component_model": row.get("component_model"),
                        "component_role": "weighted_ensemble_component",
                        "component_weight": pd.to_numeric(row.get("weight"), errors="coerce"),
                    }
                )
        except Exception:
            heavy_components = []
    return {
        "PED": [
            {
                "component_model": "hpo::PED__HPOREFINE_solver_static_convex_top18",
                "component_role": "outer_hpo_static_solver_component",
                "component_weight": 1.0,
            },
            {
                "component_model": "PED inner HPO/static-solver members",
                "component_role": "inner_component_trace",
                "component_weight": pd.NA,
            },
        ],
        "LIGHT_RUC": [
            {"component_model": "base_schiff_ols", "component_role": "OLS base level prediction", "component_weight": pd.NA},
            {
                "component_model": "residual_gbm_correction",
                "component_role": "GBM residual correction",
                "component_weight": pd.NA,
            },
        ],
        "HEAVY_RUC": heavy_components
        or [
            {"component_model": "C1-C4 heavy RUC components", "component_role": "weighted_ensemble_component", "component_weight": pd.NA}
        ],
    }


def _any_forecast_available(capabilities: pd.DataFrame) -> bool:
    if capabilities.empty or "forecast_capability_available" not in capabilities.columns:
        return False
    return capabilities["forecast_capability_available"].fillna(False).astype(bool).any()


def _forecast_status(validation: ForecastValidationResult, future: pd.DataFrame) -> str:
    if not validation.valid:
        return "validation_failed"
    if future.empty or "forecast_available" not in future.columns:
        return "governed_gap"
    by_stream = future.groupby("stream")["forecast_available"].any()
    available_count = int(by_stream.fillna(False).astype(bool).sum())
    if available_count == 0:
        return "governed_gap"
    if available_count == len(STREAM_ORDER):
        return "numeric_forecast_available"
    return "mixed_numeric_and_governed_gap"


def _forecast_capability_report(
    capabilities: pd.DataFrame,
    future: pd.DataFrame,
    components: pd.DataFrame,
    validation: ForecastValidationResult,
) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    future_group = future.groupby("stream", dropna=False) if not future.empty and "stream" in future.columns else {}
    component_group = components.groupby("stream", dropna=False) if not components.empty and "stream" in components.columns else {}
    for _, cap in capabilities.iterrows():
        stream = str(cap["stream"])
        stream_future = future_group.get_group(stream) if hasattr(future_group, "groups") and stream in future_group.groups else pd.DataFrame()
        stream_components = (
            component_group.get_group(stream) if hasattr(component_group, "groups") and stream in component_group.groups else pd.DataFrame()
        )
        forecast_available = bool(stream_future.get("forecast_available", pd.Series(dtype=bool)).fillna(False).astype(bool).any())
        numeric_count = int(pd.to_numeric(stream_future.get("forecast"), errors="coerce").notna().sum()) if not stream_future.empty else 0
        gap_reason = ""
        gap_code = None
        if not forecast_available and not stream_future.empty:
            gap_code = first_non_null(stream_future.get("gap_code"))
            gap_reason = str(first_non_null(stream_future.get("gap_reason")) or "")
        rows.append(
            {
                "stream": stream,
                "stream_label": cap.get("stream_label"),
                "model": cap.get("model"),
                "validation_status": "passed" if validation.valid else "failed",
                "forecast_available": forecast_available,
                "numeric_forecast_rows": numeric_count,
                "governed_gap_rows": int(len(stream_future) - numeric_count),
                "component_trace_rows": int(len(stream_components)),
                "capability_status": "numeric_forecast_available" if forecast_available else "governed_gap",
                "gap_code": gap_code if gap_code is not None else cap.get("gap_code"),
                "gap_reason": gap_reason if gap_reason else cap.get("gap_reason"),
                "repo_artifact_basis": cap.get("repo_artifact_basis"),
                "fixed_finalists_only": True,
                "broad_search_run": False,
            }
        )
    return pd.DataFrame(rows)


def _forecast_validation_report(validation: ForecastValidationResult, capabilities: pd.DataFrame) -> str:
    lines = [
        "# Forecast validation report",
        "",
        f"- Runner version: `{FORECAST_RUNNER_VERSION}`",
        f"- Latest known actual quarter: `{validation.latest_actual_period}`",
        f"- Forecast horizon: `{validation.forecast_periods[0]}` to `{validation.forecast_periods[-1]}`",
        f"- Input validation: `{'passed' if validation.valid else 'failed'}`",
        "- Broad candidate search run: `false`",
        "- Existing dashboard evidence/KPI/chart-source files modified: `false`",
        "",
        "## Validation messages",
        "",
    ]
    if validation.errors:
        lines.extend(f"- ERROR: {message}" for message in validation.errors)
    if validation.warnings:
        lines.extend(f"- WARNING: {message}" for message in validation.warnings)
    if not validation.errors and not validation.warnings:
        lines.append("- OK: Workbook inputs passed validation.")
    lines.extend(["", "## Forecast capability", ""])
    for _, row in capabilities.iterrows():
        lines.extend(
            [
                f"### {row['stream_label']}",
                "",
                f"- Fixed finalist: `{row['model']}`",
                f"- Status: `{row['capability_status']}`",
                f"- Gap code: `{row['gap_code']}`",
                f"- Reason: {row['gap_reason'] or 'Repo-local fixed-finalist scorer is available.'}",
                f"- Artifact basis: `{row['repo_artifact_basis']}`",
                "",
            ]
        )
    return "\n".join(lines).strip() + "\n"


def _repo_relative(root: Path, path: Path) -> str:
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return path.name


def first_non_null(series: pd.Series | None) -> Any:
    if series is None:
        return None
    values = series.dropna()
    return values.iloc[0] if not values.empty else None


def _json_safe_records(frame: pd.DataFrame) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for raw in frame.to_dict(orient="records"):
        record: dict[str, Any] = {}
        for key, value in raw.items():
            if pd.isna(value):
                record[key] = None
            elif isinstance(value, np.generic):
                record[key] = value.item()
            else:
                record[key] = value
        records.append(record)
    return records
